/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */export * from './apis/app-settings-api';
export * from './apis/background-file-api';
export * from './apis/ckeditor-samples-api';
export * from './apis/ckeditor-samples-file-api';
export * from './apis/changelog-api';
export * from './apis/chat-api';
export * from './apis/chat-message-api';
export * from './apis/configurations-api';
export * from './apis/course-api';
export * from './apis/directories-api';
export * from './apis/documents-api';
export * from './apis/equipment-api';
export * from './apis/equipment-category-api';
export * from './apis/equipment-file-links-api';
export * from './apis/equipment-files-api';
export * from './apis/equipment-image-api';
export * from './apis/equipment-location-api';
export * from './apis/equipment-maintenance-api';
export * from './apis/equipment-manufacturer-api';
export * from './apis/equipment-specification-category-api';
export * from './apis/equipment-specifications-api';
export * from './apis/external-change-listening-api';
export * from './apis/external-content-api';
export * from './apis/external-content-logo-file-api';
export * from './apis/external-content-organization-api';
export * from './apis/external-content-user-api';
export * from './apis/external-europathek-book-api';
export * from './apis/external-europathek-book-page-api';
export * from './apis/external-europathek-bookx-organization-api';
export * from './apis/external-ilias-courses-api';
export * from './apis/external-interface-topics-api';
export * from './apis/feedback-api';
export * from './apis/file-api';
export * from './apis/file-resource-api';
export * from './apis/form-api';
export * from './apis/form-file-api';
export * from './apis/form-set-api';
export * from './apis/group-api';
export * from './apis/group-task-todo-api';
export * from './apis/group-task-todo-link-api';
export * from './apis/guest-role-request-api';
export * from './apis/interface-topic-api';
export * from './apis/job-api';
export * from './apis/learning-stage-api';
export * from './apis/license-api';
export * from './apis/link-api';
export * from './apis/local-europathek-book-api';
export * from './apis/local-europathek-book-page-api';
export * from './apis/local-europathek-bookx-organization-api';
export * from './apis/logo-file-api';
export * from './apis/notification-api';
export * from './apis/organization-api';
export * from './apis/organization-footer-file-api';
export * from './apis/organization-head-file-api';
export * from './apis/organization-header-file-api';
export * from './apis/organization-settings-api';
export * from './apis/privacy-api';
export * from './apis/privacy-pdfapi';
export * from './apis/project-api';
export * from './apis/project-task-api';
export * from './apis/project-todo-api';
export * from './apis/rest-api-api';
export * from './apis/scorm-api';
export * from './apis/scorm-group-api';
export * from './apis/scorm-sco-api';
export * from './apis/skill-api';
export * from './apis/supplier-api';
export * from './apis/supplier-header-file-api';
export * from './apis/supplier-logo-file-api';
export * from './apis/tag-api';
export * from './apis/task-api';
export * from './apis/task-file-api';
export * from './apis/task-preview-image-api';
export * from './apis/task-sample-solution-api';
export * from './apis/task-set-api';
export * from './apis/task-set-translation-api';
export * from './apis/task-skill-api';
export * from './apis/task-step-api';
export * from './apis/task-step-category-api';
export * from './apis/task-step-file-api';
export * from './apis/task-todo-api';
export * from './apis/task-todo-file-api';
export * from './apis/task-todo-info-api';
export * from './apis/terms-of-use-api';
export * from './apis/terms-of-use-pdfapi';
export * from './apis/trainee-notice-api';
export * from './apis/trainee-notice-file-api';
export * from './apis/user-api';
export * from './apis/user-change-request-api';
export * from './apis/user-comment-api';
export * from './apis/user-feedback-api';
export * from './apis/user-invitation-api';
export * from './apis/user-options-api';
export * from './apis/user-privacy-api';
export * from './apis/user-terms-of-use-api';

