/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ChatMessageChatMessageRead
 */
export interface ChatMessageChatMessageRead {
    /**
     * 
     * @type {Date}
     * @memberof ChatMessageChatMessageRead
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ChatMessageChatMessageRead
     */
    updatedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof ChatMessageChatMessageRead
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ChatMessageChatMessageRead
     */
    content?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatMessageChatMessageRead
     */
    sender?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChatMessageChatMessageRead
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatMessageChatMessageRead
     */
    chat?: string;
}
