/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CourseJsonldCourseWrite
 */
export interface CourseJsonldCourseWrite {
    /**
     * 
     * @type {string | Map}
     * @memberof CourseJsonldCourseWrite
     */
    context?: string | Map;
    /**
     * 
     * @type {string}
     * @memberof CourseJsonldCourseWrite
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CourseJsonldCourseWrite
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof CourseJsonldCourseWrite
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof CourseJsonldCourseWrite
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof CourseJsonldCourseWrite
     */
    learningGoal?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof CourseJsonldCourseWrite
     */
    learningStages?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CourseJsonldCourseWrite
     */
    targetAudience?: string;
    /**
     * 
     * @type {string}
     * @memberof CourseJsonldCourseWrite
     */
    organization?: string;
    /**
     * 
     * @type {string}
     * @memberof CourseJsonldCourseWrite
     */
    lifecycle?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CourseJsonldCourseWrite
     */
    prerequisites?: Array<string>;
}
