/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DirectoriesDirectoryRead } from './directories-directory-read';
/**
 * 
 * @export
 * @interface DirectoriesDirectoryRead
 */
export interface DirectoriesDirectoryRead {
    /**
     * 
     * @type {Date}
     * @memberof DirectoriesDirectoryRead
     */
    updatedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof DirectoriesDirectoryRead
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DirectoriesDirectoryRead
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof DirectoriesDirectoryRead
     */
    owner?: string | null;
    /**
     * 
     * @type {DirectoriesDirectoryRead}
     * @memberof DirectoriesDirectoryRead
     */
    parent?: DirectoriesDirectoryRead | null;
    /**
     * 
     * @type {Array<DirectoriesDirectoryRead>}
     * @memberof DirectoriesDirectoryRead
     */
    directories?: Array<DirectoriesDirectoryRead>;
    /**
     * 
     * @type {Array<string>}
     * @memberof DirectoriesDirectoryRead
     */
    documents?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof DirectoriesDirectoryRead
     */
    isCommon?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DirectoriesDirectoryRead
     */
    organization?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof DirectoriesDirectoryRead
     */
    isRestricted?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof DirectoriesDirectoryRead
     */
    position?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof DirectoriesDirectoryRead
     */
    sharedForGroups?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof DirectoriesDirectoryRead
     */
    sharedForUsers?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof DirectoriesDirectoryRead
     */
    isGroup?: boolean;
    /**
     * 
     * @type {number}
     * @memberof DirectoriesDirectoryRead
     */
    mls1Id?: number | null;
}
