/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DirectoriesJsonld
 */
export interface DirectoriesJsonld {
    /**
     * 
     * @type {string | Map}
     * @memberof DirectoriesJsonld
     */
    context?: string | Map;
    /**
     * 
     * @type {string}
     * @memberof DirectoriesJsonld
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof DirectoriesJsonld
     */
    type?: string;
    /**
     * 
     * @type {Date}
     * @memberof DirectoriesJsonld
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof DirectoriesJsonld
     */
    updatedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof DirectoriesJsonld
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DirectoriesJsonld
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof DirectoriesJsonld
     */
    owner?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DirectoriesJsonld
     */
    parent?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof DirectoriesJsonld
     */
    directories?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof DirectoriesJsonld
     */
    documents?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof DirectoriesJsonld
     */
    isCommon?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DirectoriesJsonld
     */
    organization?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof DirectoriesJsonld
     */
    isRestricted?: boolean | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof DirectoriesJsonld
     */
    externalContents?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof DirectoriesJsonld
     */
    externalContentOrganizationsOfDirectoriesForAll?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof DirectoriesJsonld
     */
    externalContentOrganizationsOfDirectoriesForApprentice?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof DirectoriesJsonld
     */
    externalContentOrganizationsOfDirectoriesForInstructor?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof DirectoriesJsonld
     */
    position?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof DirectoriesJsonld
     */
    sharedForGroups?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof DirectoriesJsonld
     */
    sharedForUsers?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof DirectoriesJsonld
     */
    isGroup?: boolean;
    /**
     * 
     * @type {number}
     * @memberof DirectoriesJsonld
     */
    mls1Id?: number | null;
}
