/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DocumentsDocumentWrite
 */
export interface DocumentsDocumentWrite {
    /**
     * 
     * @type {string}
     * @memberof DocumentsDocumentWrite
     */
    owner?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentsDocumentWrite
     */
    parent?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof DocumentsDocumentWrite
     */
    isCommon?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DocumentsDocumentWrite
     */
    organization?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof DocumentsDocumentWrite
     */
    isRestricted?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof DocumentsDocumentWrite
     */
    isGroup?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DocumentsDocumentWrite
     */
    customFilename?: string;
}
