/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface EquipmentLocationEquipmentLocationItemWrite
 */
export interface EquipmentLocationEquipmentLocationItemWrite {
    /**
     * 
     * @type {string}
     * @memberof EquipmentLocationEquipmentLocationItemWrite
     */
    location?: string;
    /**
     * 
     * @type {string}
     * @memberof EquipmentLocationEquipmentLocationItemWrite
     */
    area?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EquipmentLocationEquipmentLocationItemWrite
     */
    comment?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof EquipmentLocationEquipmentLocationItemWrite
     */
    equipment?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof EquipmentLocationEquipmentLocationItemWrite
     */
    organization?: string;
}
