/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface EquipmentMaintenance
 */
export interface EquipmentMaintenance {
    /**
     * 
     * @type {Date}
     * @memberof EquipmentMaintenance
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof EquipmentMaintenance
     */
    updatedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof EquipmentMaintenance
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof EquipmentMaintenance
     */
    status?: string;
    /**
     * 
     * @type {Date}
     * @memberof EquipmentMaintenance
     */
    staticInterval?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof EquipmentMaintenance
     */
    dynamicInterval?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof EquipmentMaintenance
     */
    lastRun?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof EquipmentMaintenance
     */
    equipment?: string;
    /**
     * 
     * @type {string}
     * @memberof EquipmentMaintenance
     */
    task?: string;
    /**
     * 
     * @type {number}
     * @memberof EquipmentMaintenance
     */
    intervalLength?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof EquipmentMaintenance
     */
    taskTodo?: Array<string>;
}
