/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EquipmentCategoryJsonldEquipmentItemRead } from './equipment-category-jsonld-equipment-item-read';
import { EquipmentFilesJsonldEquipmentItemRead } from './equipment-files-jsonld-equipment-item-read';
import { EquipmentImageJsonldEquipmentItemRead } from './equipment-image-jsonld-equipment-item-read';
import { EquipmentMaintenanceJsonldEquipmentItemRead } from './equipment-maintenance-jsonld-equipment-item-read';
import { EquipmentManufacturerJsonldEquipmentItemRead } from './equipment-manufacturer-jsonld-equipment-item-read';
/**
 * 
 * @export
 * @interface EquipmentJsonldEquipmentItemRead
 */
export interface EquipmentJsonldEquipmentItemRead {
    /**
     * 
     * @type {string | Map}
     * @memberof EquipmentJsonldEquipmentItemRead
     */
    context?: string | Map;
    /**
     * 
     * @type {string}
     * @memberof EquipmentJsonldEquipmentItemRead
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof EquipmentJsonldEquipmentItemRead
     */
    type?: string;
    /**
     * 
     * @type {Date}
     * @memberof EquipmentJsonldEquipmentItemRead
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof EquipmentJsonldEquipmentItemRead
     */
    updatedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof EquipmentJsonldEquipmentItemRead
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof EquipmentJsonldEquipmentItemRead
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof EquipmentJsonldEquipmentItemRead
     */
    serial?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EquipmentJsonldEquipmentItemRead
     */
    creator?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EquipmentJsonldEquipmentItemRead
     */
    organization?: string;
    /**
     * 
     * @type {EquipmentManufacturerJsonldEquipmentItemRead}
     * @memberof EquipmentJsonldEquipmentItemRead
     */
    manufacturer?: EquipmentManufacturerJsonldEquipmentItemRead;
    /**
     * 
     * @type {EquipmentCategoryJsonldEquipmentItemRead}
     * @memberof EquipmentJsonldEquipmentItemRead
     */
    category?: EquipmentCategoryJsonldEquipmentItemRead;
    /**
     * 
     * @type {EquipmentImageJsonldEquipmentItemRead}
     * @memberof EquipmentJsonldEquipmentItemRead
     */
    image?: EquipmentImageJsonldEquipmentItemRead | null;
    /**
     * 
     * @type {string}
     * @memberof EquipmentJsonldEquipmentItemRead
     */
    location?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof EquipmentJsonldEquipmentItemRead
     */
    specificationCategory?: Array<string>;
    /**
     * 
     * @type {Array<EquipmentFilesJsonldEquipmentItemRead>}
     * @memberof EquipmentJsonldEquipmentItemRead
     */
    files?: Array<EquipmentFilesJsonldEquipmentItemRead>;
    /**
     * 
     * @type {Array<string>}
     * @memberof EquipmentJsonldEquipmentItemRead
     */
    fileLinks?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof EquipmentJsonldEquipmentItemRead
     */
    taskTodos?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof EquipmentJsonldEquipmentItemRead
     */
    groupTaskTodos?: Array<string>;
    /**
     * 
     * @type {Array<EquipmentMaintenanceJsonldEquipmentItemRead>}
     * @memberof EquipmentJsonldEquipmentItemRead
     */
    equipmentMaintenances?: Array<EquipmentMaintenanceJsonldEquipmentItemRead>;
}
