/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface EquipmentEquipmentWrite
 */
export interface EquipmentEquipmentWrite {
    /**
     * 
     * @type {string}
     * @memberof EquipmentEquipmentWrite
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof EquipmentEquipmentWrite
     */
    serial?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EquipmentEquipmentWrite
     */
    creator?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EquipmentEquipmentWrite
     */
    organization?: string;
    /**
     * 
     * @type {string}
     * @memberof EquipmentEquipmentWrite
     */
    manufacturer?: string;
    /**
     * 
     * @type {string}
     * @memberof EquipmentEquipmentWrite
     */
    category?: string;
    /**
     * 
     * @type {string}
     * @memberof EquipmentEquipmentWrite
     */
    image?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EquipmentEquipmentWrite
     */
    location?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof EquipmentEquipmentWrite
     */
    specificationCategory?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof EquipmentEquipmentWrite
     */
    files?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof EquipmentEquipmentWrite
     */
    fileLinks?: Array<string>;
}
