/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ExternalChangeListeningJsonld
 */
export interface ExternalChangeListeningJsonld {
    /**
     * 
     * @type {string | Map}
     * @memberof ExternalChangeListeningJsonld
     */
    context?: string | Map;
    /**
     * 
     * @type {string}
     * @memberof ExternalChangeListeningJsonld
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ExternalChangeListeningJsonld
     */
    type?: string;
    /**
     * 
     * @type {number}
     * @memberof ExternalChangeListeningJsonld
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ExternalChangeListeningJsonld
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof ExternalChangeListeningJsonld
     */
    entityType?: string;
    /**
     * 
     * @type {string}
     * @memberof ExternalChangeListeningJsonld
     */
    variant?: string;
    /**
     * 
     * @type {Date}
     * @memberof ExternalChangeListeningJsonld
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ExternalChangeListeningJsonld
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof ExternalChangeListeningJsonld
     */
    uRL?: string;
}
