/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ExternalEuropathekBookJsonldExternalEuropathekBookPageItemRead } from './external-europathek-book-jsonld-external-europathek-book-page-item-read';
/**
 * 
 * @export
 * @interface ExternalEuropathekBookPageJsonldExternalEuropathekBookPageItemRead
 */
export interface ExternalEuropathekBookPageJsonldExternalEuropathekBookPageItemRead {
    /**
     * 
     * @type {string | Map}
     * @memberof ExternalEuropathekBookPageJsonldExternalEuropathekBookPageItemRead
     */
    context?: string | Map;
    /**
     * 
     * @type {string}
     * @memberof ExternalEuropathekBookPageJsonldExternalEuropathekBookPageItemRead
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ExternalEuropathekBookPageJsonldExternalEuropathekBookPageItemRead
     */
    type?: string;
    /**
     * 
     * @type {number}
     * @memberof ExternalEuropathekBookPageJsonldExternalEuropathekBookPageItemRead
     */
    id?: number;
    /**
     * 
     * @type {ExternalEuropathekBookJsonldExternalEuropathekBookPageItemRead}
     * @memberof ExternalEuropathekBookPageJsonldExternalEuropathekBookPageItemRead
     */
    book?: ExternalEuropathekBookJsonldExternalEuropathekBookPageItemRead | null;
    /**
     * 
     * @type {string}
     * @memberof ExternalEuropathekBookPageJsonldExternalEuropathekBookPageItemRead
     */
    title?: string;
    /**
     * 
     * @type {number}
     * @memberof ExternalEuropathekBookPageJsonldExternalEuropathekBookPageItemRead
     */
    pageIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof ExternalEuropathekBookPageJsonldExternalEuropathekBookPageItemRead
     */
    parentIndex?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ExternalEuropathekBookPageJsonldExternalEuropathekBookPageItemRead
     */
    level?: number;
}
