/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ExternalEuropathekBookExternalEuropathekBookPageItemRead } from './external-europathek-book-external-europathek-book-page-item-read';
/**
 * 
 * @export
 * @interface ExternalEuropathekBookPageExternalEuropathekBookPageItemRead
 */
export interface ExternalEuropathekBookPageExternalEuropathekBookPageItemRead {
    /**
     * 
     * @type {number}
     * @memberof ExternalEuropathekBookPageExternalEuropathekBookPageItemRead
     */
    id?: number;
    /**
     * 
     * @type {ExternalEuropathekBookExternalEuropathekBookPageItemRead}
     * @memberof ExternalEuropathekBookPageExternalEuropathekBookPageItemRead
     */
    book?: ExternalEuropathekBookExternalEuropathekBookPageItemRead | null;
    /**
     * 
     * @type {string}
     * @memberof ExternalEuropathekBookPageExternalEuropathekBookPageItemRead
     */
    title?: string;
    /**
     * 
     * @type {number}
     * @memberof ExternalEuropathekBookPageExternalEuropathekBookPageItemRead
     */
    pageIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof ExternalEuropathekBookPageExternalEuropathekBookPageItemRead
     */
    parentIndex?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ExternalEuropathekBookPageExternalEuropathekBookPageItemRead
     */
    level?: number;
}
