/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ExternalContentUser
 */
export interface ExternalContentUser {
    /**
     * 
     * @type {string}
     * @memberof ExternalContentUser
     */
    externalContentOrganization?: string;
    /**
     * 
     * @type {string}
     * @memberof ExternalContentUser
     */
    user?: string;
    /**
     * 
     * @type {Date}
     * @memberof ExternalContentUser
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ExternalContentUser
     */
    updatedAt?: Date;
}
