/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ExternalEuropathekBookExternalEuropathekBookRead
 */
export interface ExternalEuropathekBookExternalEuropathekBookRead {
    /**
     * 
     * @type {number}
     * @memberof ExternalEuropathekBookExternalEuropathekBookRead
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ExternalEuropathekBookExternalEuropathekBookRead
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ExternalEuropathekBookExternalEuropathekBookRead
     */
    product?: string;
    /**
     * 
     * @type {string}
     * @memberof ExternalEuropathekBookExternalEuropathekBookRead
     */
    edition?: string;
    /**
     * 
     * @type {string}
     * @memberof ExternalEuropathekBookExternalEuropathekBookRead
     */
    licenses?: string;
    /**
     * 
     * @type {string}
     * @memberof ExternalEuropathekBookExternalEuropathekBookRead
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof ExternalEuropathekBookExternalEuropathekBookRead
     */
    internal?: string;
    /**
     * 
     * @type {string}
     * @memberof ExternalEuropathekBookExternalEuropathekBookRead
     */
    duration?: string;
    /**
     * 
     * @type {string}
     * @memberof ExternalEuropathekBookExternalEuropathekBookRead
     */
    europa?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExternalEuropathekBookExternalEuropathekBookRead
     */
    organizationSettings?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ExternalEuropathekBookExternalEuropathekBookRead
     */
    supplier?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExternalEuropathekBookExternalEuropathekBookRead
     */
    type?: string;
}
