/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface FileResourceDocumentItemReadFileReadFileResourceRead
 */
export interface FileResourceDocumentItemReadFileReadFileResourceRead {
    /**
     * 
     * @type {Date}
     * @memberof FileResourceDocumentItemReadFileReadFileResourceRead
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof FileResourceDocumentItemReadFileReadFileResourceRead
     */
    updatedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof FileResourceDocumentItemReadFileReadFileResourceRead
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof FileResourceDocumentItemReadFileReadFileResourceRead
     */
    filename?: string;
    /**
     * 
     * @type {string}
     * @memberof FileResourceDocumentItemReadFileReadFileResourceRead
     */
    originalFilename?: string;
    /**
     * 
     * @type {string}
     * @memberof FileResourceDocumentItemReadFileReadFileResourceRead
     */
    mimeType?: string;
    /**
     * 
     * @type {string}
     * @memberof FileResourceDocumentItemReadFileReadFileResourceRead
     */
    size?: string;
}
