/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface FormSetFormsetWrite
 */
export interface FormSetFormsetWrite {
    /**
     * 
     * @type {string}
     * @memberof FormSetFormsetWrite
     */
    title?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof FormSetFormsetWrite
     */
    forms?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof FormSetFormsetWrite
     */
    organization?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof FormSetFormsetWrite
     */
    isDefaultFormSet?: boolean;
}
