/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GroupTaskTodoLinkGroupTaskTodoLinkRead
 */
export interface GroupTaskTodoLinkGroupTaskTodoLinkRead {
    /**
     * 
     * @type {Date}
     * @memberof GroupTaskTodoLinkGroupTaskTodoLinkRead
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof GroupTaskTodoLinkGroupTaskTodoLinkRead
     */
    updatedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof GroupTaskTodoLinkGroupTaskTodoLinkRead
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof GroupTaskTodoLinkGroupTaskTodoLinkRead
     */
    user?: string | null;
    /**
     * 
     * @type {number}
     * @memberof GroupTaskTodoLinkGroupTaskTodoLinkRead
     */
    stepsProcessed?: number;
    /**
     * 
     * @type {string}
     * @memberof GroupTaskTodoLinkGroupTaskTodoLinkRead
     */
    groupTaskTodo?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof GroupTaskTodoLinkGroupTaskTodoLinkRead
     */
    lockAfterStep?: Array<string>;
}
