/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OrganizationGroupRead } from './organization-group-read';
/**
 * 
 * @export
 * @interface GroupGroupRead
 */
export interface GroupGroupRead {
    /**
     * 
     * @type {number}
     * @memberof GroupGroupRead
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof GroupGroupRead
     */
    title: string;
    /**
     * 
     * @type {OrganizationGroupRead}
     * @memberof GroupGroupRead
     */
    organization: OrganizationGroupRead | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof GroupGroupRead
     */
    users?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GroupGroupRead
     */
    sharedDirectories?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GroupGroupRead
     */
    sharedDocuments?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof GroupGroupRead
     */
    mls1Id?: number | null;
}
