/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GuestRoleRequestJsonldGuestRoleRequestRead
 */
export interface GuestRoleRequestJsonldGuestRoleRequestRead {
    /**
     * 
     * @type {string}
     * @memberof GuestRoleRequestJsonldGuestRoleRequestRead
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof GuestRoleRequestJsonldGuestRoleRequestRead
     */
    type?: string;
    /**
     * 
     * @type {Date}
     * @memberof GuestRoleRequestJsonldGuestRoleRequestRead
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof GuestRoleRequestJsonldGuestRoleRequestRead
     */
    updatedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof GuestRoleRequestJsonldGuestRoleRequestRead
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof GuestRoleRequestJsonldGuestRoleRequestRead
     */
    organization?: string;
    /**
     * 
     * @type {string}
     * @memberof GuestRoleRequestJsonldGuestRoleRequestRead
     */
    requester?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GuestRoleRequestJsonldGuestRoleRequestRead
     */
    approved?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GuestRoleRequestJsonldGuestRoleRequestRead
     */
    apprentice?: string;
}
