/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse200Hydrasearch } from './inline-response200-hydrasearch';
import { InlineResponse200Hydraview } from './inline-response200-hydraview';
import { TaskSetJsonldTasksetRead } from './task-set-jsonld-taskset-read';
/**
 * 
 * @export
 * @interface InlineResponse20064
 */
export interface InlineResponse20064 {
    /**
     * 
     * @type {Array<TaskSetJsonldTasksetRead>}
     * @memberof InlineResponse20064
     */
    hydramember: Array<TaskSetJsonldTasksetRead>;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20064
     */
    hydratotalItems?: number;
    /**
     * 
     * @type {InlineResponse200Hydraview}
     * @memberof InlineResponse20064
     */
    hydraview?: InlineResponse200Hydraview;
    /**
     * 
     * @type {InlineResponse200Hydrasearch}
     * @memberof InlineResponse20064
     */
    hydrasearch?: InlineResponse200Hydrasearch;
}
