/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ExternalChangeListeningJsonldExternalChangeListeningRead } from './external-change-listening-jsonld-external-change-listening-read';
import { InlineResponse200Hydrasearch } from './inline-response200-hydrasearch';
import { InlineResponse200Hydraview } from './inline-response200-hydraview';
/**
 * 
 * @export
 * @interface InlineResponse20020
 */
export interface InlineResponse20020 {
    /**
     * 
     * @type {Array<ExternalChangeListeningJsonldExternalChangeListeningRead>}
     * @memberof InlineResponse20020
     */
    hydramember: Array<ExternalChangeListeningJsonldExternalChangeListeningRead>;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20020
     */
    hydratotalItems?: number;
    /**
     * 
     * @type {InlineResponse200Hydraview}
     * @memberof InlineResponse20020
     */
    hydraview?: InlineResponse200Hydraview;
    /**
     * 
     * @type {InlineResponse200Hydrasearch}
     * @memberof InlineResponse20020
     */
    hydrasearch?: InlineResponse200Hydrasearch;
}
