/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface LearningStageJsonldCourseItemRead
 */
export interface LearningStageJsonldCourseItemRead {
    /**
     * 
     * @type {string | Map}
     * @memberof LearningStageJsonldCourseItemRead
     */
    context?: string | Map;
    /**
     * 
     * @type {string}
     * @memberof LearningStageJsonldCourseItemRead
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof LearningStageJsonldCourseItemRead
     */
    type?: string;
    /**
     * 
     * @type {number}
     * @memberof LearningStageJsonldCourseItemRead
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof LearningStageJsonldCourseItemRead
     */
    task?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof LearningStageJsonldCourseItemRead
     */
    prerequisites?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof LearningStageJsonldCourseItemRead
     */
    goals?: Array<string>;
}
