/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface LicenseJsonld
 */
export interface LicenseJsonld {
    /**
     * 
     * @type {string | Map}
     * @memberof LicenseJsonld
     */
    context?: string | Map;
    /**
     * 
     * @type {string}
     * @memberof LicenseJsonld
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof LicenseJsonld
     */
    type?: string;
    /**
     * 
     * @type {number}
     * @memberof LicenseJsonld
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof LicenseJsonld
     */
    type: string;
    /**
     * 
     * @type {number}
     * @memberof LicenseJsonld
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof LicenseJsonld
     */
    organization: string | null;
    /**
     * 
     * @type {number}
     * @memberof LicenseJsonld
     */
    available?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LicenseJsonld
     */
    setted?: number | null;
    /**
     * 
     * @type {string}
     * @memberof LicenseJsonld
     */
    note?: string | null;
}
