/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface LocalEuropathekBookPageLocalEuropathekBookPageRead
 */
export interface LocalEuropathekBookPageLocalEuropathekBookPageRead {
    /**
     * 
     * @type {number}
     * @memberof LocalEuropathekBookPageLocalEuropathekBookPageRead
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof LocalEuropathekBookPageLocalEuropathekBookPageRead
     */
    book?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LocalEuropathekBookPageLocalEuropathekBookPageRead
     */
    title?: string;
    /**
     * 
     * @type {number}
     * @memberof LocalEuropathekBookPageLocalEuropathekBookPageRead
     */
    bookPage?: number;
    /**
     * 
     * @type {string}
     * @memberof LocalEuropathekBookPageLocalEuropathekBookPageRead
     */
    previewURL?: string | null;
}
