/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface OrganizationFooterFile
 */
export interface OrganizationFooterFile {
    /**
     * 
     * @type {string}
     * @memberof OrganizationFooterFile
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationFooterFile
     */
    organization?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof OrganizationFooterFile
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof OrganizationFooterFile
     */
    updatedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof OrganizationFooterFile
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof OrganizationFooterFile
     */
    customFilename?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationFooterFile
     */
    fileResource?: string;
}
