/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PrivacyPDFPrivacyItemRead
 */
export interface PrivacyPDFPrivacyItemRead {
    /**
     * 
     * @type {string}
     * @memberof PrivacyPDFPrivacyItemRead
     */
    url?: string;
}
