/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ProjectTaskProjectTaskWrite
 */
export interface ProjectTaskProjectTaskWrite {
    /**
     * 
     * @type {string}
     * @memberof ProjectTaskProjectTaskWrite
     */
    task?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectTaskProjectTaskWrite
     */
    project?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ProjectTaskProjectTaskWrite
     */
    position?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProjectTaskProjectTaskWrite
     */
    lockAfterStep?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof ProjectTaskProjectTaskWrite
     */
    lockAfter?: boolean;
}
