/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ProjectProjectsItemWrite
 */
export interface ProjectProjectsItemWrite {
    /**
     * 
     * @type {number}
     * @memberof ProjectProjectsItemWrite
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectProjectsItemWrite
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectProjectsItemWrite
     */
    organization?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectProjectsItemWrite
     */
    creator?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectProjectsItemWrite
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectProjectsItemWrite
     */
    type?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProjectProjectsItemWrite
     */
    archived?: boolean;
}
