/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OrganizationSkillRead } from './organization-skill-read';
/**
 * 
 * @export
 * @interface SkillSkillRead
 */
export interface SkillSkillRead {
    /**
     * 
     * @type {number}
     * @memberof SkillSkillRead
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SkillSkillRead
     */
    title: string;
    /**
     * 
     * @type {OrganizationSkillRead}
     * @memberof SkillSkillRead
     */
    organization?: OrganizationSkillRead | null;
}
