/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Supplier
 */
export interface Supplier {
    /**
     * 
     * @type {Date}
     * @memberof Supplier
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Supplier
     */
    updatedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof Supplier
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Supplier
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Supplier
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof Supplier
     */
    phone: string;
    /**
     * 
     * @type {string}
     * @memberof Supplier
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Supplier
     */
    contactPersonSupplier?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Supplier
     */
    contactPersonMLS?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Supplier
     */
    website?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Supplier
     */
    organization?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Supplier
     */
    logo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Supplier
     */
    header?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof Supplier
     */
    books?: Array<string>;
}
