/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SupplierJsonldSupplierItemWrite
 */
export interface SupplierJsonldSupplierItemWrite {
    /**
     * 
     * @type {string | Map}
     * @memberof SupplierJsonldSupplierItemWrite
     */
    context?: string | Map;
    /**
     * 
     * @type {string}
     * @memberof SupplierJsonldSupplierItemWrite
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof SupplierJsonldSupplierItemWrite
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof SupplierJsonldSupplierItemWrite
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SupplierJsonldSupplierItemWrite
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof SupplierJsonldSupplierItemWrite
     */
    phone: string;
    /**
     * 
     * @type {string}
     * @memberof SupplierJsonldSupplierItemWrite
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SupplierJsonldSupplierItemWrite
     */
    contactPersonSupplier?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SupplierJsonldSupplierItemWrite
     */
    contactPersonMLS?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SupplierJsonldSupplierItemWrite
     */
    website?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SupplierJsonldSupplierItemWrite
     */
    organization?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SupplierJsonldSupplierItemWrite
     */
    logo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SupplierJsonldSupplierItemWrite
     */
    header?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof SupplierJsonldSupplierItemWrite
     */
    books?: Array<string>;
}
