/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TaskTodoInfoJsonldTaskTodoWrite } from './task-todo-info-jsonld-task-todo-write';
/**
 * 
 * @export
 * @interface TaskTodoJsonldTaskTodoWrite
 */
export interface TaskTodoJsonldTaskTodoWrite {
    /**
     * 
     * @type {string | Map}
     * @memberof TaskTodoJsonldTaskTodoWrite
     */
    context?: string | Map;
    /**
     * 
     * @type {string}
     * @memberof TaskTodoJsonldTaskTodoWrite
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskTodoJsonldTaskTodoWrite
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskTodoJsonldTaskTodoWrite
     */
    task: string;
    /**
     * 
     * @type {TaskTodoInfoJsonldTaskTodoWrite}
     * @memberof TaskTodoJsonldTaskTodoWrite
     */
    taskTodoInfo?: TaskTodoInfoJsonldTaskTodoWrite | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof TaskTodoJsonldTaskTodoWrite
     */
    shuffleQuestions?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof TaskTodoJsonldTaskTodoWrite
     */
    formAnswers?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof TaskTodoJsonldTaskTodoWrite
     */
    scormAnswers?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof TaskTodoJsonldTaskTodoWrite
     */
    assigner?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TaskTodoJsonldTaskTodoWrite
     */
    user: string | null;
    /**
     * 
     * @type {Date}
     * @memberof TaskTodoJsonldTaskTodoWrite
     */
    startTime?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof TaskTodoJsonldTaskTodoWrite
     */
    endTime?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof TaskTodoJsonldTaskTodoWrite
     */
    note?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof TaskTodoJsonldTaskTodoWrite
     */
    instructorsToNotify?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof TaskTodoJsonldTaskTodoWrite
     */
    usedHelpingTopics?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof TaskTodoJsonldTaskTodoWrite
     */
    equipments?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof TaskTodoJsonldTaskTodoWrite
     */
    mls1Id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof TaskTodoJsonldTaskTodoWrite
     */
    notice?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TaskTodoJsonldTaskTodoWrite
     */
    organization?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskTodoJsonldTaskTodoWrite
     */
    equipmentMaintenance?: string | null;
}
