/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TaskPreviewImageJsonldTaskRead
 */
export interface TaskPreviewImageJsonldTaskRead {
    /**
     * 
     * @type {string | Map}
     * @memberof TaskPreviewImageJsonldTaskRead
     */
    context?: string | Map;
    /**
     * 
     * @type {string}
     * @memberof TaskPreviewImageJsonldTaskRead
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskPreviewImageJsonldTaskRead
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskPreviewImageJsonldTaskRead
     */
    url?: string;
}
