/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TaskTodoInfoTaskTodoItemWrite } from './task-todo-info-task-todo-item-write';
/**
 * 
 * @export
 * @interface TaskTodoTaskTodoItemWrite
 */
export interface TaskTodoTaskTodoItemWrite {
    /**
     * 
     * @type {string}
     * @memberof TaskTodoTaskTodoItemWrite
     */
    task: string;
    /**
     * 
     * @type {TaskTodoInfoTaskTodoItemWrite}
     * @memberof TaskTodoTaskTodoItemWrite
     */
    taskTodoInfo?: TaskTodoInfoTaskTodoItemWrite | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof TaskTodoTaskTodoItemWrite
     */
    formAnswers?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof TaskTodoTaskTodoItemWrite
     */
    scormAnswers?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof TaskTodoTaskTodoItemWrite
     */
    instructorsToNotify?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof TaskTodoTaskTodoItemWrite
     */
    files?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof TaskTodoTaskTodoItemWrite
     */
    reactivated?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TaskTodoTaskTodoItemWrite
     */
    archived?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TaskTodoTaskTodoItemWrite
     */
    showToLearners?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TaskTodoTaskTodoItemWrite
     */
    showInStatistic?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof TaskTodoTaskTodoItemWrite
     */
    usedHelpingTopics?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof TaskTodoTaskTodoItemWrite
     */
    equipments?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof TaskTodoTaskTodoItemWrite
     */
    notice?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TaskTodoTaskTodoItemWrite
     */
    equipmentMaintenance?: string | null;
}
