/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TaskStepFileTaskStepItemRead } from './task-step-file-task-step-item-read';
import { TaskStepTaskStepItemRead } from './task-step-task-step-item-read';
/**
 * 
 * @export
 * @interface TaskStepTaskStepItemRead
 */
export interface TaskStepTaskStepItemRead {
    /**
     * 
     * @type {Date}
     * @memberof TaskStepTaskStepItemRead
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TaskStepTaskStepItemRead
     */
    updatedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof TaskStepTaskStepItemRead
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TaskStepTaskStepItemRead
     */
    title: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof TaskStepTaskStepItemRead
     */
    content?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof TaskStepTaskStepItemRead
     */
    helpingTopics?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof TaskStepTaskStepItemRead
     */
    taskStepCategory?: string | null;
    /**
     * 
     * @type {TaskStepTaskStepItemRead}
     * @memberof TaskStepTaskStepItemRead
     */
    parent?: TaskStepTaskStepItemRead | null;
    /**
     * 
     * @type {Array<TaskStepTaskStepItemRead>}
     * @memberof TaskStepTaskStepItemRead
     */
    taskSteps?: Array<TaskStepTaskStepItemRead>;
    /**
     * 
     * @type {number}
     * @memberof TaskStepTaskStepItemRead
     */
    position?: number;
    /**
     * 
     * @type {string}
     * @memberof TaskStepTaskStepItemRead
     */
    task?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof TaskStepTaskStepItemRead
     */
    stop?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof TaskStepTaskStepItemRead
     */
    connectedForms?: Array<string>;
    /**
     * 
     * @type {Array<TaskStepFileTaskStepItemRead>}
     * @memberof TaskStepTaskStepItemRead
     */
    files?: Array<TaskStepFileTaskStepItemRead>;
    /**
     * 
     * @type {number}
     * @memberof TaskStepTaskStepItemRead
     */
    mls1Id?: number | null;
}
