/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TermsOfUsePDFTermsOfUseItemRead } from './terms-of-use-pdfterms-of-use-item-read';
/**
 * 
 * @export
 * @interface TermsOfUseTermsOfUseItemRead
 */
export interface TermsOfUseTermsOfUseItemRead {
    /**
     * 
     * @type {Date}
     * @memberof TermsOfUseTermsOfUseItemRead
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TermsOfUseTermsOfUseItemRead
     */
    updatedAt?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof TermsOfUseTermsOfUseItemRead
     */
    active?: boolean;
    /**
     * 
     * @type {number}
     * @memberof TermsOfUseTermsOfUseItemRead
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TermsOfUseTermsOfUseItemRead
     */
    excerpt?: string;
    /**
     * 
     * @type {string}
     * @memberof TermsOfUseTermsOfUseItemRead
     */
    text?: string;
    /**
     * 
     * @type {string}
     * @memberof TermsOfUseTermsOfUseItemRead
     */
    organization?: string | null;
    /**
     * 
     * @type {TermsOfUsePDFTermsOfUseItemRead}
     * @memberof TermsOfUseTermsOfUseItemRead
     */
    termsOfUsePDF?: TermsOfUsePDFTermsOfUseItemRead | null;
}
