/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TraineeNoticeFileTraineeNoticeItemRead } from './trainee-notice-file-trainee-notice-item-read';
/**
 * 
 * @export
 * @interface TraineeNoticeTraineeNoticeItemRead
 */
export interface TraineeNoticeTraineeNoticeItemRead {
    /**
     * 
     * @type {Date}
     * @memberof TraineeNoticeTraineeNoticeItemRead
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TraineeNoticeTraineeNoticeItemRead
     */
    updatedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof TraineeNoticeTraineeNoticeItemRead
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TraineeNoticeTraineeNoticeItemRead
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof TraineeNoticeTraineeNoticeItemRead
     */
    content?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TraineeNoticeTraineeNoticeItemRead
     */
    user?: string;
    /**
     * 
     * @type {string}
     * @memberof TraineeNoticeTraineeNoticeItemRead
     */
    taskStep?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TraineeNoticeTraineeNoticeItemRead
     */
    taskTodo?: string | null;
    /**
     * 
     * @type {Array<TraineeNoticeFileTraineeNoticeItemRead>}
     * @memberof TraineeNoticeTraineeNoticeItemRead
     */
    files?: Array<TraineeNoticeFileTraineeNoticeItemRead>;
}
