/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TaskStepJsonldTraineeNoticeRead } from './task-step-jsonld-trainee-notice-read';
import { TraineeNoticeFileJsonldTraineeNoticeRead } from './trainee-notice-file-jsonld-trainee-notice-read';
/**
 * 
 * @export
 * @interface TraineeNoticeJsonldTraineeNoticeRead
 */
export interface TraineeNoticeJsonldTraineeNoticeRead {
    /**
     * 
     * @type {string}
     * @memberof TraineeNoticeJsonldTraineeNoticeRead
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TraineeNoticeJsonldTraineeNoticeRead
     */
    type?: string;
    /**
     * 
     * @type {Date}
     * @memberof TraineeNoticeJsonldTraineeNoticeRead
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TraineeNoticeJsonldTraineeNoticeRead
     */
    updatedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof TraineeNoticeJsonldTraineeNoticeRead
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TraineeNoticeJsonldTraineeNoticeRead
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof TraineeNoticeJsonldTraineeNoticeRead
     */
    content?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TraineeNoticeJsonldTraineeNoticeRead
     */
    user?: string;
    /**
     * 
     * @type {TaskStepJsonldTraineeNoticeRead}
     * @memberof TraineeNoticeJsonldTraineeNoticeRead
     */
    taskStep?: TaskStepJsonldTraineeNoticeRead | null;
    /**
     * 
     * @type {string}
     * @memberof TraineeNoticeJsonldTraineeNoticeRead
     */
    taskTodo?: string | null;
    /**
     * 
     * @type {Array<TraineeNoticeFileJsonldTraineeNoticeRead>}
     * @memberof TraineeNoticeJsonldTraineeNoticeRead
     */
    files?: Array<TraineeNoticeFileJsonldTraineeNoticeRead>;
    /**
     * 
     * @type {number}
     * @memberof TraineeNoticeJsonldTraineeNoticeRead
     */
    mls1Id?: number | null;
}
