/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserJsonldUserChangeRequestRead } from './user-jsonld-user-change-request-read';
/**
 * 
 * @export
 * @interface UserChangeRequestJsonldUserChangeRequestRead
 */
export interface UserChangeRequestJsonldUserChangeRequestRead {
    /**
     * 
     * @type {string}
     * @memberof UserChangeRequestJsonldUserChangeRequestRead
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserChangeRequestJsonldUserChangeRequestRead
     */
    type?: string;
    /**
     * 
     * @type {string | Map}
     * @memberof UserChangeRequestJsonldUserChangeRequestRead
     */
    context?: string | Map;
    /**
     * 
     * @type {number}
     * @memberof UserChangeRequestJsonldUserChangeRequestRead
     */
    id?: number;
    /**
     * 
     * @type {UserJsonldUserChangeRequestRead}
     * @memberof UserChangeRequestJsonldUserChangeRequestRead
     */
    user?: UserJsonldUserChangeRequestRead;
    /**
     * 
     * @type {UserJsonldUserChangeRequestRead}
     * @memberof UserChangeRequestJsonldUserChangeRequestRead
     */
    confirmUser?: UserJsonldUserChangeRequestRead | null;
    /**
     * 
     * @type {string}
     * @memberof UserChangeRequestJsonldUserChangeRequestRead
     */
    action?: string;
    /**
     * 
     * @type {string}
     * @memberof UserChangeRequestJsonldUserChangeRequestRead
     */
    value?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserChangeRequestJsonldUserChangeRequestRead
     */
    isAccepted?: boolean | null;
    /**
     * 
     * @type {Date}
     * @memberof UserChangeRequestJsonldUserChangeRequestRead
     */
    acceptedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof UserChangeRequestJsonldUserChangeRequestRead
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UserChangeRequestJsonldUserChangeRequestRead
     */
    updatedAt?: Date;
}
