/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UserCommentUserCommentItemWrite
 */
export interface UserCommentUserCommentItemWrite {
    /**
     * 
     * @type {string}
     * @memberof UserCommentUserCommentItemWrite
     */
    user: string;
    /**
     * 
     * @type {string}
     * @memberof UserCommentUserCommentItemWrite
     */
    organization: string;
    /**
     * 
     * @type {string}
     * @memberof UserCommentUserCommentItemWrite
     */
    content?: string;
}
