/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UserCommentJsonld
 */
export interface UserCommentJsonld {
    /**
     * 
     * @type {string | Map}
     * @memberof UserCommentJsonld
     */
    context?: string | Map;
    /**
     * 
     * @type {string}
     * @memberof UserCommentJsonld
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserCommentJsonld
     */
    type?: string;
    /**
     * 
     * @type {Date}
     * @memberof UserCommentJsonld
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UserCommentJsonld
     */
    updatedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof UserCommentJsonld
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof UserCommentJsonld
     */
    lastEditor?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserCommentJsonld
     */
    user: string;
    /**
     * 
     * @type {string}
     * @memberof UserCommentJsonld
     */
    organization: string;
    /**
     * 
     * @type {string}
     * @memberof UserCommentJsonld
     */
    content?: string;
}
