/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { EquipmentFileLinksEquipmentFileLinksItemWrite } from '../models';
import { EquipmentFileLinksEquipmentFileLinksWrite } from '../models';
import { EquipmentFileLinksJsonld } from '../models';
import { EquipmentFileLinksJsonldEquipmentFileLinksItemRead } from '../models';
import { EquipmentFileLinksJsonldEquipmentFileLinksItemWrite } from '../models';
import { EquipmentFileLinksJsonldEquipmentFileLinksWrite } from '../models';
import { InlineResponse20012 } from '../models';
/**
 * EquipmentFileLinksApi - axios parameter creator
 * @export
 */
export const EquipmentFileLinksApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Removes the EquipmentFileLinks resource.
         * @summary Removes the EquipmentFileLinks resource.
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteEquipmentFileLinksItem: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling deleteEquipmentFileLinksItem.');
            }
            const localVarPath = `/mls-api/equipment-file-links/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("oauth", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves the collection of EquipmentFileLinks resources.
         * @summary Retrieves the collection of EquipmentFileLinks resources.
         * @param {number} [page] The collection page number
         * @param {number} [itemsPerPage] The number of items per page
         * @param {boolean} [pagination] Enable or disable pagination
         * @param {string} [equipment] 
         * @param {Array<string>} [equipment] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEquipmentFileLinksCollection: async (page?: number, itemsPerPage?: number, pagination?: boolean, equipment?: string, equipment?: Array<string>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/mls-api/equipment-file-links`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("oauth", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (itemsPerPage !== undefined) {
                localVarQueryParameter['itemsPerPage'] = itemsPerPage;
            }

            if (pagination !== undefined) {
                localVarQueryParameter['pagination'] = pagination;
            }

            if (equipment !== undefined) {
                localVarQueryParameter['equipment'] = equipment;
            }

            if (equipment) {
                localVarQueryParameter['equipment[]'] = equipment;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves a EquipmentFileLinks resource.
         * @summary Retrieves a EquipmentFileLinks resource.
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEquipmentFileLinksItem: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling getEquipmentFileLinksItem.');
            }
            const localVarPath = `/mls-api/equipment-file-links/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("oauth", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Creates a EquipmentFileLinks resource.
         * @summary Creates a EquipmentFileLinks resource.
         * @param {EquipmentFileLinksJsonldEquipmentFileLinksWrite} body The new EquipmentFileLinks resource
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postEquipmentFileLinksCollection: async (body: EquipmentFileLinksJsonldEquipmentFileLinksWrite, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling postEquipmentFileLinksCollection.');
            }
            const localVarPath = `/mls-api/equipment-file-links`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("oauth", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/ld+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Creates a EquipmentFileLinks resource.
         * @summary Creates a EquipmentFileLinks resource.
         * @param {EquipmentFileLinksJsonldEquipmentFileLinksWrite} body The new EquipmentFileLinks resource
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postEquipmentFileLinksCollection: async (body: EquipmentFileLinksJsonldEquipmentFileLinksWrite, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling postEquipmentFileLinksCollection.');
            }
            const localVarPath = `/mls-api/equipment-file-links`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("oauth", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/ld+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Replaces the EquipmentFileLinks resource.
         * @summary Replaces the EquipmentFileLinks resource.
         * @param {EquipmentFileLinksJsonldEquipmentFileLinksItemWrite} body The updated EquipmentFileLinks resource
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putEquipmentFileLinksItem: async (body: EquipmentFileLinksJsonldEquipmentFileLinksItemWrite, id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling putEquipmentFileLinksItem.');
            }
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling putEquipmentFileLinksItem.');
            }
            const localVarPath = `/mls-api/equipment-file-links/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("oauth", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/ld+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Replaces the EquipmentFileLinks resource.
         * @summary Replaces the EquipmentFileLinks resource.
         * @param {EquipmentFileLinksJsonldEquipmentFileLinksItemWrite} body The updated EquipmentFileLinks resource
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putEquipmentFileLinksItem: async (body: EquipmentFileLinksJsonldEquipmentFileLinksItemWrite, id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling putEquipmentFileLinksItem.');
            }
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling putEquipmentFileLinksItem.');
            }
            const localVarPath = `/mls-api/equipment-file-links/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("oauth", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/ld+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EquipmentFileLinksApi - functional programming interface
 * @export
 */
export const EquipmentFileLinksApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Removes the EquipmentFileLinks resource.
         * @summary Removes the EquipmentFileLinks resource.
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteEquipmentFileLinksItem(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await EquipmentFileLinksApiAxiosParamCreator(configuration).deleteEquipmentFileLinksItem(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Retrieves the collection of EquipmentFileLinks resources.
         * @summary Retrieves the collection of EquipmentFileLinks resources.
         * @param {number} [page] The collection page number
         * @param {number} [itemsPerPage] The number of items per page
         * @param {boolean} [pagination] Enable or disable pagination
         * @param {string} [equipment] 
         * @param {Array<string>} [equipment] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEquipmentFileLinksCollection(page?: number, itemsPerPage?: number, pagination?: boolean, equipment?: string, equipment?: Array<string>, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse20012>>> {
            const localVarAxiosArgs = await EquipmentFileLinksApiAxiosParamCreator(configuration).getEquipmentFileLinksCollection(page, itemsPerPage, pagination, equipment, equipment, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Retrieves a EquipmentFileLinks resource.
         * @summary Retrieves a EquipmentFileLinks resource.
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEquipmentFileLinksItem(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<EquipmentFileLinksJsonldEquipmentFileLinksItemRead>>> {
            const localVarAxiosArgs = await EquipmentFileLinksApiAxiosParamCreator(configuration).getEquipmentFileLinksItem(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Creates a EquipmentFileLinks resource.
         * @summary Creates a EquipmentFileLinks resource.
         * @param {EquipmentFileLinksJsonldEquipmentFileLinksWrite} body The new EquipmentFileLinks resource
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postEquipmentFileLinksCollection(body: EquipmentFileLinksJsonldEquipmentFileLinksWrite, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<EquipmentFileLinksJsonld>>> {
            const localVarAxiosArgs = await EquipmentFileLinksApiAxiosParamCreator(configuration).postEquipmentFileLinksCollection(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Creates a EquipmentFileLinks resource.
         * @summary Creates a EquipmentFileLinks resource.
         * @param {EquipmentFileLinksJsonldEquipmentFileLinksWrite} body The new EquipmentFileLinks resource
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postEquipmentFileLinksCollection(body: EquipmentFileLinksJsonldEquipmentFileLinksWrite, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<EquipmentFileLinksJsonld>>> {
            const localVarAxiosArgs = await EquipmentFileLinksApiAxiosParamCreator(configuration).postEquipmentFileLinksCollection(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Replaces the EquipmentFileLinks resource.
         * @summary Replaces the EquipmentFileLinks resource.
         * @param {EquipmentFileLinksJsonldEquipmentFileLinksItemWrite} body The updated EquipmentFileLinks resource
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putEquipmentFileLinksItem(body: EquipmentFileLinksJsonldEquipmentFileLinksItemWrite, id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<EquipmentFileLinksJsonld>>> {
            const localVarAxiosArgs = await EquipmentFileLinksApiAxiosParamCreator(configuration).putEquipmentFileLinksItem(body, id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Replaces the EquipmentFileLinks resource.
         * @summary Replaces the EquipmentFileLinks resource.
         * @param {EquipmentFileLinksJsonldEquipmentFileLinksItemWrite} body The updated EquipmentFileLinks resource
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putEquipmentFileLinksItem(body: EquipmentFileLinksJsonldEquipmentFileLinksItemWrite, id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<EquipmentFileLinksJsonld>>> {
            const localVarAxiosArgs = await EquipmentFileLinksApiAxiosParamCreator(configuration).putEquipmentFileLinksItem(body, id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * EquipmentFileLinksApi - factory interface
 * @export
 */
export const EquipmentFileLinksApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Removes the EquipmentFileLinks resource.
         * @summary Removes the EquipmentFileLinks resource.
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteEquipmentFileLinksItem(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return EquipmentFileLinksApiFp(configuration).deleteEquipmentFileLinksItem(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves the collection of EquipmentFileLinks resources.
         * @summary Retrieves the collection of EquipmentFileLinks resources.
         * @param {number} [page] The collection page number
         * @param {number} [itemsPerPage] The number of items per page
         * @param {boolean} [pagination] Enable or disable pagination
         * @param {string} [equipment] 
         * @param {Array<string>} [equipment] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEquipmentFileLinksCollection(page?: number, itemsPerPage?: number, pagination?: boolean, equipment?: string, equipment?: Array<string>, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse20012>> {
            return EquipmentFileLinksApiFp(configuration).getEquipmentFileLinksCollection(page, itemsPerPage, pagination, equipment, equipment, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves a EquipmentFileLinks resource.
         * @summary Retrieves a EquipmentFileLinks resource.
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEquipmentFileLinksItem(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<EquipmentFileLinksJsonldEquipmentFileLinksItemRead>> {
            return EquipmentFileLinksApiFp(configuration).getEquipmentFileLinksItem(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Creates a EquipmentFileLinks resource.
         * @summary Creates a EquipmentFileLinks resource.
         * @param {EquipmentFileLinksJsonldEquipmentFileLinksWrite} body The new EquipmentFileLinks resource
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postEquipmentFileLinksCollection(body: EquipmentFileLinksJsonldEquipmentFileLinksWrite, options?: AxiosRequestConfig): Promise<AxiosResponse<EquipmentFileLinksJsonld>> {
            return EquipmentFileLinksApiFp(configuration).postEquipmentFileLinksCollection(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Creates a EquipmentFileLinks resource.
         * @summary Creates a EquipmentFileLinks resource.
         * @param {EquipmentFileLinksJsonldEquipmentFileLinksWrite} body The new EquipmentFileLinks resource
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postEquipmentFileLinksCollection(body: EquipmentFileLinksJsonldEquipmentFileLinksWrite, options?: AxiosRequestConfig): Promise<AxiosResponse<EquipmentFileLinksJsonld>> {
            return EquipmentFileLinksApiFp(configuration).postEquipmentFileLinksCollection(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Replaces the EquipmentFileLinks resource.
         * @summary Replaces the EquipmentFileLinks resource.
         * @param {EquipmentFileLinksJsonldEquipmentFileLinksItemWrite} body The updated EquipmentFileLinks resource
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putEquipmentFileLinksItem(body: EquipmentFileLinksJsonldEquipmentFileLinksItemWrite, id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<EquipmentFileLinksJsonld>> {
            return EquipmentFileLinksApiFp(configuration).putEquipmentFileLinksItem(body, id, options).then((request) => request(axios, basePath));
        },
        /**
         * Replaces the EquipmentFileLinks resource.
         * @summary Replaces the EquipmentFileLinks resource.
         * @param {EquipmentFileLinksJsonldEquipmentFileLinksItemWrite} body The updated EquipmentFileLinks resource
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putEquipmentFileLinksItem(body: EquipmentFileLinksJsonldEquipmentFileLinksItemWrite, id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<EquipmentFileLinksJsonld>> {
            return EquipmentFileLinksApiFp(configuration).putEquipmentFileLinksItem(body, id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * EquipmentFileLinksApi - object-oriented interface
 * @export
 * @class EquipmentFileLinksApi
 * @extends {BaseAPI}
 */
export class EquipmentFileLinksApi extends BaseAPI {
    /**
     * Removes the EquipmentFileLinks resource.
     * @summary Removes the EquipmentFileLinks resource.
     * @param {string} id Resource identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EquipmentFileLinksApi
     */
    public async deleteEquipmentFileLinksItem(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return EquipmentFileLinksApiFp(this.configuration).deleteEquipmentFileLinksItem(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Retrieves the collection of EquipmentFileLinks resources.
     * @summary Retrieves the collection of EquipmentFileLinks resources.
     * @param {number} [page] The collection page number
     * @param {number} [itemsPerPage] The number of items per page
     * @param {boolean} [pagination] Enable or disable pagination
     * @param {string} [equipment] 
     * @param {Array<string>} [equipment] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EquipmentFileLinksApi
     */
    public async getEquipmentFileLinksCollection(page?: number, itemsPerPage?: number, pagination?: boolean, equipment?: string, equipment?: Array<string>, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse20012>> {
        return EquipmentFileLinksApiFp(this.configuration).getEquipmentFileLinksCollection(page, itemsPerPage, pagination, equipment, equipment, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Retrieves a EquipmentFileLinks resource.
     * @summary Retrieves a EquipmentFileLinks resource.
     * @param {string} id Resource identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EquipmentFileLinksApi
     */
    public async getEquipmentFileLinksItem(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<EquipmentFileLinksJsonldEquipmentFileLinksItemRead>> {
        return EquipmentFileLinksApiFp(this.configuration).getEquipmentFileLinksItem(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Creates a EquipmentFileLinks resource.
     * @summary Creates a EquipmentFileLinks resource.
     * @param {EquipmentFileLinksJsonldEquipmentFileLinksWrite} body The new EquipmentFileLinks resource
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EquipmentFileLinksApi
     */
    public async postEquipmentFileLinksCollection(body: EquipmentFileLinksJsonldEquipmentFileLinksWrite, options?: AxiosRequestConfig) : Promise<AxiosResponse<EquipmentFileLinksJsonld>> {
        return EquipmentFileLinksApiFp(this.configuration).postEquipmentFileLinksCollection(body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Creates a EquipmentFileLinks resource.
     * @summary Creates a EquipmentFileLinks resource.
     * @param {EquipmentFileLinksJsonldEquipmentFileLinksWrite} body The new EquipmentFileLinks resource
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EquipmentFileLinksApi
     */
    public async postEquipmentFileLinksCollection(body: EquipmentFileLinksJsonldEquipmentFileLinksWrite, options?: AxiosRequestConfig) : Promise<AxiosResponse<EquipmentFileLinksJsonld>> {
        return EquipmentFileLinksApiFp(this.configuration).postEquipmentFileLinksCollection(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Replaces the EquipmentFileLinks resource.
     * @summary Replaces the EquipmentFileLinks resource.
     * @param {EquipmentFileLinksJsonldEquipmentFileLinksItemWrite} body The updated EquipmentFileLinks resource
     * @param {string} id Resource identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EquipmentFileLinksApi
     */
    public async putEquipmentFileLinksItem(body: EquipmentFileLinksJsonldEquipmentFileLinksItemWrite, id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<EquipmentFileLinksJsonld>> {
        return EquipmentFileLinksApiFp(this.configuration).putEquipmentFileLinksItem(body, id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Replaces the EquipmentFileLinks resource.
     * @summary Replaces the EquipmentFileLinks resource.
     * @param {EquipmentFileLinksJsonldEquipmentFileLinksItemWrite} body The updated EquipmentFileLinks resource
     * @param {string} id Resource identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EquipmentFileLinksApi
     */
    public async putEquipmentFileLinksItem(body: EquipmentFileLinksJsonldEquipmentFileLinksItemWrite, id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<EquipmentFileLinksJsonld>> {
        return EquipmentFileLinksApiFp(this.configuration).putEquipmentFileLinksItem(body, id, options).then((request) => request(this.axios, this.basePath));
    }
}
