/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { GroupGroupItemWrite } from '../models';
import { GroupGroupWrite } from '../models';
import { GroupJsonld } from '../models';
import { GroupJsonldGroupItemRead } from '../models';
import { GroupJsonldGroupItemWrite } from '../models';
import { GroupJsonldGroupWrite } from '../models';
import { InlineResponse20036 } from '../models';
/**
 * GroupApi - axios parameter creator
 * @export
 */
export const GroupApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Removes the Group resource.
         * @summary Removes the Group resource.
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteGroupItem: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling deleteGroupItem.');
            }
            const localVarPath = `/mls-api/groups/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("oauth", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves the collection of Group resources.
         * @summary Retrieves the collection of Group resources.
         * @param {number} [page] The collection page number
         * @param {number} [itemsPerPage] The number of items per page
         * @param {boolean} [pagination] Enable or disable pagination
         * @param {string} [title] 
         * @param {number} [mls1Id] 
         * @param {Array<number>} [mls1Id] 
         * @param {string} [organization] 
         * @param {Array<string>} [organization] 
         * @param {string} [sharedDirectories] 
         * @param {Array<string>} [sharedDirectories] 
         * @param {string} [sharedDocuments] 
         * @param {Array<string>} [sharedDocuments] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGroupCollection: async (page?: number, itemsPerPage?: number, pagination?: boolean, title?: string, mls1Id?: number, mls1Id?: Array<number>, organization?: string, organization?: Array<string>, sharedDirectories?: string, sharedDirectories?: Array<string>, sharedDocuments?: string, sharedDocuments?: Array<string>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/mls-api/groups`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("oauth", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (itemsPerPage !== undefined) {
                localVarQueryParameter['itemsPerPage'] = itemsPerPage;
            }

            if (pagination !== undefined) {
                localVarQueryParameter['pagination'] = pagination;
            }

            if (title !== undefined) {
                localVarQueryParameter['title'] = title;
            }

            if (mls1Id !== undefined) {
                localVarQueryParameter['mls1Id'] = mls1Id;
            }

            if (mls1Id) {
                localVarQueryParameter['mls1Id[]'] = mls1Id;
            }

            if (organization !== undefined) {
                localVarQueryParameter['organization'] = organization;
            }

            if (organization) {
                localVarQueryParameter['organization[]'] = organization;
            }

            if (sharedDirectories !== undefined) {
                localVarQueryParameter['sharedDirectories'] = sharedDirectories;
            }

            if (sharedDirectories) {
                localVarQueryParameter['sharedDirectories[]'] = sharedDirectories;
            }

            if (sharedDocuments !== undefined) {
                localVarQueryParameter['sharedDocuments'] = sharedDocuments;
            }

            if (sharedDocuments) {
                localVarQueryParameter['sharedDocuments[]'] = sharedDocuments;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves a Group resource.
         * @summary Retrieves a Group resource.
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGroupItem: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling getGroupItem.');
            }
            const localVarPath = `/mls-api/groups/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("oauth", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Creates a Group resource.
         * @summary Creates a Group resource.
         * @param {GroupJsonldGroupWrite} body The new Group resource
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postGroupCollection: async (body: GroupJsonldGroupWrite, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling postGroupCollection.');
            }
            const localVarPath = `/mls-api/groups`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("oauth", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/ld+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Creates a Group resource.
         * @summary Creates a Group resource.
         * @param {GroupJsonldGroupWrite} body The new Group resource
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postGroupCollection: async (body: GroupJsonldGroupWrite, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling postGroupCollection.');
            }
            const localVarPath = `/mls-api/groups`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("oauth", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/ld+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Replaces the Group resource.
         * @summary Replaces the Group resource.
         * @param {GroupJsonldGroupItemWrite} body The updated Group resource
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putGroupItem: async (body: GroupJsonldGroupItemWrite, id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling putGroupItem.');
            }
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling putGroupItem.');
            }
            const localVarPath = `/mls-api/groups/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("oauth", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/ld+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Replaces the Group resource.
         * @summary Replaces the Group resource.
         * @param {GroupJsonldGroupItemWrite} body The updated Group resource
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putGroupItem: async (body: GroupJsonldGroupItemWrite, id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling putGroupItem.');
            }
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling putGroupItem.');
            }
            const localVarPath = `/mls-api/groups/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("oauth", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/ld+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GroupApi - functional programming interface
 * @export
 */
export const GroupApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Removes the Group resource.
         * @summary Removes the Group resource.
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteGroupItem(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await GroupApiAxiosParamCreator(configuration).deleteGroupItem(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Retrieves the collection of Group resources.
         * @summary Retrieves the collection of Group resources.
         * @param {number} [page] The collection page number
         * @param {number} [itemsPerPage] The number of items per page
         * @param {boolean} [pagination] Enable or disable pagination
         * @param {string} [title] 
         * @param {number} [mls1Id] 
         * @param {Array<number>} [mls1Id] 
         * @param {string} [organization] 
         * @param {Array<string>} [organization] 
         * @param {string} [sharedDirectories] 
         * @param {Array<string>} [sharedDirectories] 
         * @param {string} [sharedDocuments] 
         * @param {Array<string>} [sharedDocuments] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getGroupCollection(page?: number, itemsPerPage?: number, pagination?: boolean, title?: string, mls1Id?: number, mls1Id?: Array<number>, organization?: string, organization?: Array<string>, sharedDirectories?: string, sharedDirectories?: Array<string>, sharedDocuments?: string, sharedDocuments?: Array<string>, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse20036>>> {
            const localVarAxiosArgs = await GroupApiAxiosParamCreator(configuration).getGroupCollection(page, itemsPerPage, pagination, title, mls1Id, mls1Id, organization, organization, sharedDirectories, sharedDirectories, sharedDocuments, sharedDocuments, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Retrieves a Group resource.
         * @summary Retrieves a Group resource.
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getGroupItem(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<GroupJsonldGroupItemRead>>> {
            const localVarAxiosArgs = await GroupApiAxiosParamCreator(configuration).getGroupItem(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Creates a Group resource.
         * @summary Creates a Group resource.
         * @param {GroupJsonldGroupWrite} body The new Group resource
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postGroupCollection(body: GroupJsonldGroupWrite, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<GroupJsonld>>> {
            const localVarAxiosArgs = await GroupApiAxiosParamCreator(configuration).postGroupCollection(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Creates a Group resource.
         * @summary Creates a Group resource.
         * @param {GroupJsonldGroupWrite} body The new Group resource
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postGroupCollection(body: GroupJsonldGroupWrite, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<GroupJsonld>>> {
            const localVarAxiosArgs = await GroupApiAxiosParamCreator(configuration).postGroupCollection(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Replaces the Group resource.
         * @summary Replaces the Group resource.
         * @param {GroupJsonldGroupItemWrite} body The updated Group resource
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putGroupItem(body: GroupJsonldGroupItemWrite, id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<GroupJsonld>>> {
            const localVarAxiosArgs = await GroupApiAxiosParamCreator(configuration).putGroupItem(body, id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Replaces the Group resource.
         * @summary Replaces the Group resource.
         * @param {GroupJsonldGroupItemWrite} body The updated Group resource
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putGroupItem(body: GroupJsonldGroupItemWrite, id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<GroupJsonld>>> {
            const localVarAxiosArgs = await GroupApiAxiosParamCreator(configuration).putGroupItem(body, id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * GroupApi - factory interface
 * @export
 */
export const GroupApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Removes the Group resource.
         * @summary Removes the Group resource.
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteGroupItem(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return GroupApiFp(configuration).deleteGroupItem(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves the collection of Group resources.
         * @summary Retrieves the collection of Group resources.
         * @param {number} [page] The collection page number
         * @param {number} [itemsPerPage] The number of items per page
         * @param {boolean} [pagination] Enable or disable pagination
         * @param {string} [title] 
         * @param {number} [mls1Id] 
         * @param {Array<number>} [mls1Id] 
         * @param {string} [organization] 
         * @param {Array<string>} [organization] 
         * @param {string} [sharedDirectories] 
         * @param {Array<string>} [sharedDirectories] 
         * @param {string} [sharedDocuments] 
         * @param {Array<string>} [sharedDocuments] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getGroupCollection(page?: number, itemsPerPage?: number, pagination?: boolean, title?: string, mls1Id?: number, mls1Id?: Array<number>, organization?: string, organization?: Array<string>, sharedDirectories?: string, sharedDirectories?: Array<string>, sharedDocuments?: string, sharedDocuments?: Array<string>, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse20036>> {
            return GroupApiFp(configuration).getGroupCollection(page, itemsPerPage, pagination, title, mls1Id, mls1Id, organization, organization, sharedDirectories, sharedDirectories, sharedDocuments, sharedDocuments, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves a Group resource.
         * @summary Retrieves a Group resource.
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getGroupItem(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<GroupJsonldGroupItemRead>> {
            return GroupApiFp(configuration).getGroupItem(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Creates a Group resource.
         * @summary Creates a Group resource.
         * @param {GroupJsonldGroupWrite} body The new Group resource
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postGroupCollection(body: GroupJsonldGroupWrite, options?: AxiosRequestConfig): Promise<AxiosResponse<GroupJsonld>> {
            return GroupApiFp(configuration).postGroupCollection(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Creates a Group resource.
         * @summary Creates a Group resource.
         * @param {GroupJsonldGroupWrite} body The new Group resource
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postGroupCollection(body: GroupJsonldGroupWrite, options?: AxiosRequestConfig): Promise<AxiosResponse<GroupJsonld>> {
            return GroupApiFp(configuration).postGroupCollection(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Replaces the Group resource.
         * @summary Replaces the Group resource.
         * @param {GroupJsonldGroupItemWrite} body The updated Group resource
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putGroupItem(body: GroupJsonldGroupItemWrite, id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<GroupJsonld>> {
            return GroupApiFp(configuration).putGroupItem(body, id, options).then((request) => request(axios, basePath));
        },
        /**
         * Replaces the Group resource.
         * @summary Replaces the Group resource.
         * @param {GroupJsonldGroupItemWrite} body The updated Group resource
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putGroupItem(body: GroupJsonldGroupItemWrite, id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<GroupJsonld>> {
            return GroupApiFp(configuration).putGroupItem(body, id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GroupApi - object-oriented interface
 * @export
 * @class GroupApi
 * @extends {BaseAPI}
 */
export class GroupApi extends BaseAPI {
    /**
     * Removes the Group resource.
     * @summary Removes the Group resource.
     * @param {string} id Resource identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupApi
     */
    public async deleteGroupItem(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return GroupApiFp(this.configuration).deleteGroupItem(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Retrieves the collection of Group resources.
     * @summary Retrieves the collection of Group resources.
     * @param {number} [page] The collection page number
     * @param {number} [itemsPerPage] The number of items per page
     * @param {boolean} [pagination] Enable or disable pagination
     * @param {string} [title] 
     * @param {number} [mls1Id] 
     * @param {Array<number>} [mls1Id] 
     * @param {string} [organization] 
     * @param {Array<string>} [organization] 
     * @param {string} [sharedDirectories] 
     * @param {Array<string>} [sharedDirectories] 
     * @param {string} [sharedDocuments] 
     * @param {Array<string>} [sharedDocuments] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupApi
     */
    public async getGroupCollection(page?: number, itemsPerPage?: number, pagination?: boolean, title?: string, mls1Id?: number, mls1Id?: Array<number>, organization?: string, organization?: Array<string>, sharedDirectories?: string, sharedDirectories?: Array<string>, sharedDocuments?: string, sharedDocuments?: Array<string>, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse20036>> {
        return GroupApiFp(this.configuration).getGroupCollection(page, itemsPerPage, pagination, title, mls1Id, mls1Id, organization, organization, sharedDirectories, sharedDirectories, sharedDocuments, sharedDocuments, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Retrieves a Group resource.
     * @summary Retrieves a Group resource.
     * @param {string} id Resource identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupApi
     */
    public async getGroupItem(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<GroupJsonldGroupItemRead>> {
        return GroupApiFp(this.configuration).getGroupItem(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Creates a Group resource.
     * @summary Creates a Group resource.
     * @param {GroupJsonldGroupWrite} body The new Group resource
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupApi
     */
    public async postGroupCollection(body: GroupJsonldGroupWrite, options?: AxiosRequestConfig) : Promise<AxiosResponse<GroupJsonld>> {
        return GroupApiFp(this.configuration).postGroupCollection(body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Creates a Group resource.
     * @summary Creates a Group resource.
     * @param {GroupJsonldGroupWrite} body The new Group resource
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupApi
     */
    public async postGroupCollection(body: GroupJsonldGroupWrite, options?: AxiosRequestConfig) : Promise<AxiosResponse<GroupJsonld>> {
        return GroupApiFp(this.configuration).postGroupCollection(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Replaces the Group resource.
     * @summary Replaces the Group resource.
     * @param {GroupJsonldGroupItemWrite} body The updated Group resource
     * @param {string} id Resource identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupApi
     */
    public async putGroupItem(body: GroupJsonldGroupItemWrite, id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<GroupJsonld>> {
        return GroupApiFp(this.configuration).putGroupItem(body, id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Replaces the Group resource.
     * @summary Replaces the Group resource.
     * @param {GroupJsonldGroupItemWrite} body The updated Group resource
     * @param {string} id Resource identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupApi
     */
    public async putGroupItem(body: GroupJsonldGroupItemWrite, id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<GroupJsonld>> {
        return GroupApiFp(this.configuration).putGroupItem(body, id, options).then((request) => request(this.axios, this.basePath));
    }
}
