/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { InlineResponse20062 } from '../models';
import { TaskSampleSolutionJsonld } from '../models';
/**
 * TaskSampleSolutionApi - axios parameter creator
 * @export
 */
export const TaskSampleSolutionApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Removes the TaskSampleSolution resource.
         * @summary Removes the TaskSampleSolution resource.
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTaskSampleSolutionItem: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling deleteTaskSampleSolutionItem.');
            }
            const localVarPath = `/mls-api/task-sample-solutions/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("oauth", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves the collection of TaskSampleSolution resources.
         * @summary Retrieves the collection of TaskSampleSolution resources.
         * @param {number} [page] The collection page number
         * @param {number} [itemsPerPage] The number of items per page
         * @param {boolean} [pagination] Enable or disable pagination
         * @param {string} [fileResource] 
         * @param {Array<string>} [fileResource] 
         * @param {string} [fileResourceOriginalFilename] 
         * @param {string} [fileResourceMimeType] 
         * @param {Array<string>} [fileResourceMimeType] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTaskSampleSolutionCollection: async (page?: number, itemsPerPage?: number, pagination?: boolean, fileResource?: string, fileResource?: Array<string>, fileResourceOriginalFilename?: string, fileResourceMimeType?: string, fileResourceMimeType?: Array<string>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/mls-api/task-sample-solutions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("oauth", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (itemsPerPage !== undefined) {
                localVarQueryParameter['itemsPerPage'] = itemsPerPage;
            }

            if (pagination !== undefined) {
                localVarQueryParameter['pagination'] = pagination;
            }

            if (fileResource !== undefined) {
                localVarQueryParameter['fileResource'] = fileResource;
            }

            if (fileResource) {
                localVarQueryParameter['fileResource[]'] = fileResource;
            }

            if (fileResourceOriginalFilename !== undefined) {
                localVarQueryParameter['fileResource.originalFilename'] = fileResourceOriginalFilename;
            }

            if (fileResourceMimeType !== undefined) {
                localVarQueryParameter['fileResource.mimeType'] = fileResourceMimeType;
            }

            if (fileResourceMimeType) {
                localVarQueryParameter['fileResource.mimeType[]'] = fileResourceMimeType;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves a TaskSampleSolution resource.
         * @summary Retrieves a TaskSampleSolution resource.
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTaskSampleSolutionItem: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling getTaskSampleSolutionItem.');
            }
            const localVarPath = `/mls-api/task-sample-solutions/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("oauth", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TaskSampleSolutionApi - functional programming interface
 * @export
 */
export const TaskSampleSolutionApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Removes the TaskSampleSolution resource.
         * @summary Removes the TaskSampleSolution resource.
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteTaskSampleSolutionItem(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await TaskSampleSolutionApiAxiosParamCreator(configuration).deleteTaskSampleSolutionItem(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Retrieves the collection of TaskSampleSolution resources.
         * @summary Retrieves the collection of TaskSampleSolution resources.
         * @param {number} [page] The collection page number
         * @param {number} [itemsPerPage] The number of items per page
         * @param {boolean} [pagination] Enable or disable pagination
         * @param {string} [fileResource] 
         * @param {Array<string>} [fileResource] 
         * @param {string} [fileResourceOriginalFilename] 
         * @param {string} [fileResourceMimeType] 
         * @param {Array<string>} [fileResourceMimeType] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTaskSampleSolutionCollection(page?: number, itemsPerPage?: number, pagination?: boolean, fileResource?: string, fileResource?: Array<string>, fileResourceOriginalFilename?: string, fileResourceMimeType?: string, fileResourceMimeType?: Array<string>, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse20062>>> {
            const localVarAxiosArgs = await TaskSampleSolutionApiAxiosParamCreator(configuration).getTaskSampleSolutionCollection(page, itemsPerPage, pagination, fileResource, fileResource, fileResourceOriginalFilename, fileResourceMimeType, fileResourceMimeType, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Retrieves a TaskSampleSolution resource.
         * @summary Retrieves a TaskSampleSolution resource.
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTaskSampleSolutionItem(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<TaskSampleSolutionJsonld>>> {
            const localVarAxiosArgs = await TaskSampleSolutionApiAxiosParamCreator(configuration).getTaskSampleSolutionItem(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * TaskSampleSolutionApi - factory interface
 * @export
 */
export const TaskSampleSolutionApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Removes the TaskSampleSolution resource.
         * @summary Removes the TaskSampleSolution resource.
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteTaskSampleSolutionItem(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return TaskSampleSolutionApiFp(configuration).deleteTaskSampleSolutionItem(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves the collection of TaskSampleSolution resources.
         * @summary Retrieves the collection of TaskSampleSolution resources.
         * @param {number} [page] The collection page number
         * @param {number} [itemsPerPage] The number of items per page
         * @param {boolean} [pagination] Enable or disable pagination
         * @param {string} [fileResource] 
         * @param {Array<string>} [fileResource] 
         * @param {string} [fileResourceOriginalFilename] 
         * @param {string} [fileResourceMimeType] 
         * @param {Array<string>} [fileResourceMimeType] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTaskSampleSolutionCollection(page?: number, itemsPerPage?: number, pagination?: boolean, fileResource?: string, fileResource?: Array<string>, fileResourceOriginalFilename?: string, fileResourceMimeType?: string, fileResourceMimeType?: Array<string>, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse20062>> {
            return TaskSampleSolutionApiFp(configuration).getTaskSampleSolutionCollection(page, itemsPerPage, pagination, fileResource, fileResource, fileResourceOriginalFilename, fileResourceMimeType, fileResourceMimeType, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves a TaskSampleSolution resource.
         * @summary Retrieves a TaskSampleSolution resource.
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTaskSampleSolutionItem(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<TaskSampleSolutionJsonld>> {
            return TaskSampleSolutionApiFp(configuration).getTaskSampleSolutionItem(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TaskSampleSolutionApi - object-oriented interface
 * @export
 * @class TaskSampleSolutionApi
 * @extends {BaseAPI}
 */
export class TaskSampleSolutionApi extends BaseAPI {
    /**
     * Removes the TaskSampleSolution resource.
     * @summary Removes the TaskSampleSolution resource.
     * @param {string} id Resource identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TaskSampleSolutionApi
     */
    public async deleteTaskSampleSolutionItem(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return TaskSampleSolutionApiFp(this.configuration).deleteTaskSampleSolutionItem(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Retrieves the collection of TaskSampleSolution resources.
     * @summary Retrieves the collection of TaskSampleSolution resources.
     * @param {number} [page] The collection page number
     * @param {number} [itemsPerPage] The number of items per page
     * @param {boolean} [pagination] Enable or disable pagination
     * @param {string} [fileResource] 
     * @param {Array<string>} [fileResource] 
     * @param {string} [fileResourceOriginalFilename] 
     * @param {string} [fileResourceMimeType] 
     * @param {Array<string>} [fileResourceMimeType] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TaskSampleSolutionApi
     */
    public async getTaskSampleSolutionCollection(page?: number, itemsPerPage?: number, pagination?: boolean, fileResource?: string, fileResource?: Array<string>, fileResourceOriginalFilename?: string, fileResourceMimeType?: string, fileResourceMimeType?: Array<string>, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse20062>> {
        return TaskSampleSolutionApiFp(this.configuration).getTaskSampleSolutionCollection(page, itemsPerPage, pagination, fileResource, fileResource, fileResourceOriginalFilename, fileResourceMimeType, fileResourceMimeType, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Retrieves a TaskSampleSolution resource.
     * @summary Retrieves a TaskSampleSolution resource.
     * @param {string} id Resource identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TaskSampleSolutionApi
     */
    public async getTaskSampleSolutionItem(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<TaskSampleSolutionJsonld>> {
        return TaskSampleSolutionApiFp(this.configuration).getTaskSampleSolutionItem(id, options).then((request) => request(this.axios, this.basePath));
    }
}
