/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { InlineResponse20063 } from '../models';
import { TaskSetTranslationJsonld } from '../models';
import { TaskSetTranslationJsonldTasksetTranslationItemRead } from '../models';
import { TaskSetTranslationJsonldTasksetTranslationItemWrite } from '../models';
import { TaskSetTranslationJsonldTasksetTranslationWrite } from '../models';
import { TaskSetTranslationTasksetTranslationItemWrite } from '../models';
import { TaskSetTranslationTasksetTranslationWrite } from '../models';
/**
 * TaskSetTranslationApi - axios parameter creator
 * @export
 */
export const TaskSetTranslationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Removes the TaskSetTranslation resource.
         * @summary Removes the TaskSetTranslation resource.
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTaskSetTranslationItem: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling deleteTaskSetTranslationItem.');
            }
            const localVarPath = `/mls-api/task-set-translations/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("oauth", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves the collection of TaskSetTranslation resources.
         * @summary Retrieves the collection of TaskSetTranslation resources.
         * @param {number} [page] The collection page number
         * @param {number} [itemsPerPage] The number of items per page
         * @param {boolean} [pagination] Enable or disable pagination
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTaskSetTranslationCollection: async (page?: number, itemsPerPage?: number, pagination?: boolean, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/mls-api/task-set-translations`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("oauth", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (itemsPerPage !== undefined) {
                localVarQueryParameter['itemsPerPage'] = itemsPerPage;
            }

            if (pagination !== undefined) {
                localVarQueryParameter['pagination'] = pagination;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves a TaskSetTranslation resource.
         * @summary Retrieves a TaskSetTranslation resource.
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTaskSetTranslationItem: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling getTaskSetTranslationItem.');
            }
            const localVarPath = `/mls-api/task-set-translations/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("oauth", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Creates a TaskSetTranslation resource.
         * @summary Creates a TaskSetTranslation resource.
         * @param {TaskSetTranslationJsonldTasksetTranslationWrite} body The new TaskSetTranslation resource
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postTaskSetTranslationCollection: async (body: TaskSetTranslationJsonldTasksetTranslationWrite, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling postTaskSetTranslationCollection.');
            }
            const localVarPath = `/mls-api/task-set-translations`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("oauth", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/ld+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Creates a TaskSetTranslation resource.
         * @summary Creates a TaskSetTranslation resource.
         * @param {TaskSetTranslationJsonldTasksetTranslationWrite} body The new TaskSetTranslation resource
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postTaskSetTranslationCollection: async (body: TaskSetTranslationJsonldTasksetTranslationWrite, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling postTaskSetTranslationCollection.');
            }
            const localVarPath = `/mls-api/task-set-translations`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("oauth", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/ld+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Replaces the TaskSetTranslation resource.
         * @summary Replaces the TaskSetTranslation resource.
         * @param {TaskSetTranslationJsonldTasksetTranslationItemWrite} body The updated TaskSetTranslation resource
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putTaskSetTranslationItem: async (body: TaskSetTranslationJsonldTasksetTranslationItemWrite, id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling putTaskSetTranslationItem.');
            }
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling putTaskSetTranslationItem.');
            }
            const localVarPath = `/mls-api/task-set-translations/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("oauth", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/ld+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Replaces the TaskSetTranslation resource.
         * @summary Replaces the TaskSetTranslation resource.
         * @param {TaskSetTranslationJsonldTasksetTranslationItemWrite} body The updated TaskSetTranslation resource
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putTaskSetTranslationItem: async (body: TaskSetTranslationJsonldTasksetTranslationItemWrite, id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling putTaskSetTranslationItem.');
            }
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling putTaskSetTranslationItem.');
            }
            const localVarPath = `/mls-api/task-set-translations/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("oauth", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/ld+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TaskSetTranslationApi - functional programming interface
 * @export
 */
export const TaskSetTranslationApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Removes the TaskSetTranslation resource.
         * @summary Removes the TaskSetTranslation resource.
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteTaskSetTranslationItem(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await TaskSetTranslationApiAxiosParamCreator(configuration).deleteTaskSetTranslationItem(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Retrieves the collection of TaskSetTranslation resources.
         * @summary Retrieves the collection of TaskSetTranslation resources.
         * @param {number} [page] The collection page number
         * @param {number} [itemsPerPage] The number of items per page
         * @param {boolean} [pagination] Enable or disable pagination
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTaskSetTranslationCollection(page?: number, itemsPerPage?: number, pagination?: boolean, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse20063>>> {
            const localVarAxiosArgs = await TaskSetTranslationApiAxiosParamCreator(configuration).getTaskSetTranslationCollection(page, itemsPerPage, pagination, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Retrieves a TaskSetTranslation resource.
         * @summary Retrieves a TaskSetTranslation resource.
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTaskSetTranslationItem(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<TaskSetTranslationJsonldTasksetTranslationItemRead>>> {
            const localVarAxiosArgs = await TaskSetTranslationApiAxiosParamCreator(configuration).getTaskSetTranslationItem(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Creates a TaskSetTranslation resource.
         * @summary Creates a TaskSetTranslation resource.
         * @param {TaskSetTranslationJsonldTasksetTranslationWrite} body The new TaskSetTranslation resource
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postTaskSetTranslationCollection(body: TaskSetTranslationJsonldTasksetTranslationWrite, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<TaskSetTranslationJsonld>>> {
            const localVarAxiosArgs = await TaskSetTranslationApiAxiosParamCreator(configuration).postTaskSetTranslationCollection(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Creates a TaskSetTranslation resource.
         * @summary Creates a TaskSetTranslation resource.
         * @param {TaskSetTranslationJsonldTasksetTranslationWrite} body The new TaskSetTranslation resource
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postTaskSetTranslationCollection(body: TaskSetTranslationJsonldTasksetTranslationWrite, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<TaskSetTranslationJsonld>>> {
            const localVarAxiosArgs = await TaskSetTranslationApiAxiosParamCreator(configuration).postTaskSetTranslationCollection(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Replaces the TaskSetTranslation resource.
         * @summary Replaces the TaskSetTranslation resource.
         * @param {TaskSetTranslationJsonldTasksetTranslationItemWrite} body The updated TaskSetTranslation resource
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putTaskSetTranslationItem(body: TaskSetTranslationJsonldTasksetTranslationItemWrite, id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<TaskSetTranslationJsonld>>> {
            const localVarAxiosArgs = await TaskSetTranslationApiAxiosParamCreator(configuration).putTaskSetTranslationItem(body, id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Replaces the TaskSetTranslation resource.
         * @summary Replaces the TaskSetTranslation resource.
         * @param {TaskSetTranslationJsonldTasksetTranslationItemWrite} body The updated TaskSetTranslation resource
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putTaskSetTranslationItem(body: TaskSetTranslationJsonldTasksetTranslationItemWrite, id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<TaskSetTranslationJsonld>>> {
            const localVarAxiosArgs = await TaskSetTranslationApiAxiosParamCreator(configuration).putTaskSetTranslationItem(body, id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * TaskSetTranslationApi - factory interface
 * @export
 */
export const TaskSetTranslationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Removes the TaskSetTranslation resource.
         * @summary Removes the TaskSetTranslation resource.
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteTaskSetTranslationItem(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return TaskSetTranslationApiFp(configuration).deleteTaskSetTranslationItem(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves the collection of TaskSetTranslation resources.
         * @summary Retrieves the collection of TaskSetTranslation resources.
         * @param {number} [page] The collection page number
         * @param {number} [itemsPerPage] The number of items per page
         * @param {boolean} [pagination] Enable or disable pagination
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTaskSetTranslationCollection(page?: number, itemsPerPage?: number, pagination?: boolean, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse20063>> {
            return TaskSetTranslationApiFp(configuration).getTaskSetTranslationCollection(page, itemsPerPage, pagination, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves a TaskSetTranslation resource.
         * @summary Retrieves a TaskSetTranslation resource.
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTaskSetTranslationItem(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<TaskSetTranslationJsonldTasksetTranslationItemRead>> {
            return TaskSetTranslationApiFp(configuration).getTaskSetTranslationItem(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Creates a TaskSetTranslation resource.
         * @summary Creates a TaskSetTranslation resource.
         * @param {TaskSetTranslationJsonldTasksetTranslationWrite} body The new TaskSetTranslation resource
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postTaskSetTranslationCollection(body: TaskSetTranslationJsonldTasksetTranslationWrite, options?: AxiosRequestConfig): Promise<AxiosResponse<TaskSetTranslationJsonld>> {
            return TaskSetTranslationApiFp(configuration).postTaskSetTranslationCollection(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Creates a TaskSetTranslation resource.
         * @summary Creates a TaskSetTranslation resource.
         * @param {TaskSetTranslationJsonldTasksetTranslationWrite} body The new TaskSetTranslation resource
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postTaskSetTranslationCollection(body: TaskSetTranslationJsonldTasksetTranslationWrite, options?: AxiosRequestConfig): Promise<AxiosResponse<TaskSetTranslationJsonld>> {
            return TaskSetTranslationApiFp(configuration).postTaskSetTranslationCollection(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Replaces the TaskSetTranslation resource.
         * @summary Replaces the TaskSetTranslation resource.
         * @param {TaskSetTranslationJsonldTasksetTranslationItemWrite} body The updated TaskSetTranslation resource
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putTaskSetTranslationItem(body: TaskSetTranslationJsonldTasksetTranslationItemWrite, id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<TaskSetTranslationJsonld>> {
            return TaskSetTranslationApiFp(configuration).putTaskSetTranslationItem(body, id, options).then((request) => request(axios, basePath));
        },
        /**
         * Replaces the TaskSetTranslation resource.
         * @summary Replaces the TaskSetTranslation resource.
         * @param {TaskSetTranslationJsonldTasksetTranslationItemWrite} body The updated TaskSetTranslation resource
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putTaskSetTranslationItem(body: TaskSetTranslationJsonldTasksetTranslationItemWrite, id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<TaskSetTranslationJsonld>> {
            return TaskSetTranslationApiFp(configuration).putTaskSetTranslationItem(body, id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TaskSetTranslationApi - object-oriented interface
 * @export
 * @class TaskSetTranslationApi
 * @extends {BaseAPI}
 */
export class TaskSetTranslationApi extends BaseAPI {
    /**
     * Removes the TaskSetTranslation resource.
     * @summary Removes the TaskSetTranslation resource.
     * @param {string} id Resource identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TaskSetTranslationApi
     */
    public async deleteTaskSetTranslationItem(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return TaskSetTranslationApiFp(this.configuration).deleteTaskSetTranslationItem(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Retrieves the collection of TaskSetTranslation resources.
     * @summary Retrieves the collection of TaskSetTranslation resources.
     * @param {number} [page] The collection page number
     * @param {number} [itemsPerPage] The number of items per page
     * @param {boolean} [pagination] Enable or disable pagination
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TaskSetTranslationApi
     */
    public async getTaskSetTranslationCollection(page?: number, itemsPerPage?: number, pagination?: boolean, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse20063>> {
        return TaskSetTranslationApiFp(this.configuration).getTaskSetTranslationCollection(page, itemsPerPage, pagination, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Retrieves a TaskSetTranslation resource.
     * @summary Retrieves a TaskSetTranslation resource.
     * @param {string} id Resource identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TaskSetTranslationApi
     */
    public async getTaskSetTranslationItem(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<TaskSetTranslationJsonldTasksetTranslationItemRead>> {
        return TaskSetTranslationApiFp(this.configuration).getTaskSetTranslationItem(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Creates a TaskSetTranslation resource.
     * @summary Creates a TaskSetTranslation resource.
     * @param {TaskSetTranslationJsonldTasksetTranslationWrite} body The new TaskSetTranslation resource
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TaskSetTranslationApi
     */
    public async postTaskSetTranslationCollection(body: TaskSetTranslationJsonldTasksetTranslationWrite, options?: AxiosRequestConfig) : Promise<AxiosResponse<TaskSetTranslationJsonld>> {
        return TaskSetTranslationApiFp(this.configuration).postTaskSetTranslationCollection(body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Creates a TaskSetTranslation resource.
     * @summary Creates a TaskSetTranslation resource.
     * @param {TaskSetTranslationJsonldTasksetTranslationWrite} body The new TaskSetTranslation resource
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TaskSetTranslationApi
     */
    public async postTaskSetTranslationCollection(body: TaskSetTranslationJsonldTasksetTranslationWrite, options?: AxiosRequestConfig) : Promise<AxiosResponse<TaskSetTranslationJsonld>> {
        return TaskSetTranslationApiFp(this.configuration).postTaskSetTranslationCollection(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Replaces the TaskSetTranslation resource.
     * @summary Replaces the TaskSetTranslation resource.
     * @param {TaskSetTranslationJsonldTasksetTranslationItemWrite} body The updated TaskSetTranslation resource
     * @param {string} id Resource identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TaskSetTranslationApi
     */
    public async putTaskSetTranslationItem(body: TaskSetTranslationJsonldTasksetTranslationItemWrite, id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<TaskSetTranslationJsonld>> {
        return TaskSetTranslationApiFp(this.configuration).putTaskSetTranslationItem(body, id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Replaces the TaskSetTranslation resource.
     * @summary Replaces the TaskSetTranslation resource.
     * @param {TaskSetTranslationJsonldTasksetTranslationItemWrite} body The updated TaskSetTranslation resource
     * @param {string} id Resource identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TaskSetTranslationApi
     */
    public async putTaskSetTranslationItem(body: TaskSetTranslationJsonldTasksetTranslationItemWrite, id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<TaskSetTranslationJsonld>> {
        return TaskSetTranslationApiFp(this.configuration).putTaskSetTranslationItem(body, id, options).then((request) => request(this.axios, this.basePath));
    }
}
