/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { InlineResponse20082 } from '../models';
import { UserTermsOfUseJsonld } from '../models';
import { UserTermsOfUseJsonldUserTermsOfUseItemRead } from '../models';
import { UserTermsOfUseJsonldUserTermsOfUseWrite } from '../models';
import { UserTermsOfUseUserTermsOfUseWrite } from '../models';
/**
 * UserTermsOfUseApi - axios parameter creator
 * @export
 */
export const UserTermsOfUseApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieves the collection of UserTermsOfUse resources.
         * @summary Retrieves the collection of UserTermsOfUse resources.
         * @param {number} [page] The collection page number
         * @param {number} [itemsPerPage] The number of items per page
         * @param {boolean} [pagination] Enable or disable pagination
         * @param {string} [user] 
         * @param {Array<string>} [user] 
         * @param {string} [termsOfUse] 
         * @param {Array<string>} [termsOfUse] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserTermsOfUseCollection: async (page?: number, itemsPerPage?: number, pagination?: boolean, user?: string, user?: Array<string>, termsOfUse?: string, termsOfUse?: Array<string>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/mls-api/user-terms-of-uses`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("oauth", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (itemsPerPage !== undefined) {
                localVarQueryParameter['itemsPerPage'] = itemsPerPage;
            }

            if (pagination !== undefined) {
                localVarQueryParameter['pagination'] = pagination;
            }

            if (user !== undefined) {
                localVarQueryParameter['user'] = user;
            }

            if (user) {
                localVarQueryParameter['user[]'] = user;
            }

            if (termsOfUse !== undefined) {
                localVarQueryParameter['termsOfUse'] = termsOfUse;
            }

            if (termsOfUse) {
                localVarQueryParameter['termsOfUse[]'] = termsOfUse;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves a UserTermsOfUse resource.
         * @summary Retrieves a UserTermsOfUse resource.
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserTermsOfUseItem: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling getUserTermsOfUseItem.');
            }
            const localVarPath = `/mls-api/user-terms-of-uses/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("oauth", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Creates a UserTermsOfUse resource.
         * @summary Creates a UserTermsOfUse resource.
         * @param {UserTermsOfUseJsonldUserTermsOfUseWrite} body The new UserTermsOfUse resource
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postUserTermsOfUseCollection: async (body: UserTermsOfUseJsonldUserTermsOfUseWrite, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling postUserTermsOfUseCollection.');
            }
            const localVarPath = `/mls-api/user-terms-of-uses`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("oauth", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/ld+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Creates a UserTermsOfUse resource.
         * @summary Creates a UserTermsOfUse resource.
         * @param {UserTermsOfUseJsonldUserTermsOfUseWrite} body The new UserTermsOfUse resource
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postUserTermsOfUseCollection: async (body: UserTermsOfUseJsonldUserTermsOfUseWrite, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling postUserTermsOfUseCollection.');
            }
            const localVarPath = `/mls-api/user-terms-of-uses`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("oauth", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/ld+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserTermsOfUseApi - functional programming interface
 * @export
 */
export const UserTermsOfUseApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Retrieves the collection of UserTermsOfUse resources.
         * @summary Retrieves the collection of UserTermsOfUse resources.
         * @param {number} [page] The collection page number
         * @param {number} [itemsPerPage] The number of items per page
         * @param {boolean} [pagination] Enable or disable pagination
         * @param {string} [user] 
         * @param {Array<string>} [user] 
         * @param {string} [termsOfUse] 
         * @param {Array<string>} [termsOfUse] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserTermsOfUseCollection(page?: number, itemsPerPage?: number, pagination?: boolean, user?: string, user?: Array<string>, termsOfUse?: string, termsOfUse?: Array<string>, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse20082>>> {
            const localVarAxiosArgs = await UserTermsOfUseApiAxiosParamCreator(configuration).getUserTermsOfUseCollection(page, itemsPerPage, pagination, user, user, termsOfUse, termsOfUse, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Retrieves a UserTermsOfUse resource.
         * @summary Retrieves a UserTermsOfUse resource.
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserTermsOfUseItem(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<UserTermsOfUseJsonldUserTermsOfUseItemRead>>> {
            const localVarAxiosArgs = await UserTermsOfUseApiAxiosParamCreator(configuration).getUserTermsOfUseItem(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Creates a UserTermsOfUse resource.
         * @summary Creates a UserTermsOfUse resource.
         * @param {UserTermsOfUseJsonldUserTermsOfUseWrite} body The new UserTermsOfUse resource
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postUserTermsOfUseCollection(body: UserTermsOfUseJsonldUserTermsOfUseWrite, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<UserTermsOfUseJsonld>>> {
            const localVarAxiosArgs = await UserTermsOfUseApiAxiosParamCreator(configuration).postUserTermsOfUseCollection(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Creates a UserTermsOfUse resource.
         * @summary Creates a UserTermsOfUse resource.
         * @param {UserTermsOfUseJsonldUserTermsOfUseWrite} body The new UserTermsOfUse resource
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postUserTermsOfUseCollection(body: UserTermsOfUseJsonldUserTermsOfUseWrite, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<UserTermsOfUseJsonld>>> {
            const localVarAxiosArgs = await UserTermsOfUseApiAxiosParamCreator(configuration).postUserTermsOfUseCollection(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * UserTermsOfUseApi - factory interface
 * @export
 */
export const UserTermsOfUseApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Retrieves the collection of UserTermsOfUse resources.
         * @summary Retrieves the collection of UserTermsOfUse resources.
         * @param {number} [page] The collection page number
         * @param {number} [itemsPerPage] The number of items per page
         * @param {boolean} [pagination] Enable or disable pagination
         * @param {string} [user] 
         * @param {Array<string>} [user] 
         * @param {string} [termsOfUse] 
         * @param {Array<string>} [termsOfUse] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserTermsOfUseCollection(page?: number, itemsPerPage?: number, pagination?: boolean, user?: string, user?: Array<string>, termsOfUse?: string, termsOfUse?: Array<string>, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse20082>> {
            return UserTermsOfUseApiFp(configuration).getUserTermsOfUseCollection(page, itemsPerPage, pagination, user, user, termsOfUse, termsOfUse, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves a UserTermsOfUse resource.
         * @summary Retrieves a UserTermsOfUse resource.
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserTermsOfUseItem(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<UserTermsOfUseJsonldUserTermsOfUseItemRead>> {
            return UserTermsOfUseApiFp(configuration).getUserTermsOfUseItem(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Creates a UserTermsOfUse resource.
         * @summary Creates a UserTermsOfUse resource.
         * @param {UserTermsOfUseJsonldUserTermsOfUseWrite} body The new UserTermsOfUse resource
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postUserTermsOfUseCollection(body: UserTermsOfUseJsonldUserTermsOfUseWrite, options?: AxiosRequestConfig): Promise<AxiosResponse<UserTermsOfUseJsonld>> {
            return UserTermsOfUseApiFp(configuration).postUserTermsOfUseCollection(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Creates a UserTermsOfUse resource.
         * @summary Creates a UserTermsOfUse resource.
         * @param {UserTermsOfUseJsonldUserTermsOfUseWrite} body The new UserTermsOfUse resource
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postUserTermsOfUseCollection(body: UserTermsOfUseJsonldUserTermsOfUseWrite, options?: AxiosRequestConfig): Promise<AxiosResponse<UserTermsOfUseJsonld>> {
            return UserTermsOfUseApiFp(configuration).postUserTermsOfUseCollection(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserTermsOfUseApi - object-oriented interface
 * @export
 * @class UserTermsOfUseApi
 * @extends {BaseAPI}
 */
export class UserTermsOfUseApi extends BaseAPI {
    /**
     * Retrieves the collection of UserTermsOfUse resources.
     * @summary Retrieves the collection of UserTermsOfUse resources.
     * @param {number} [page] The collection page number
     * @param {number} [itemsPerPage] The number of items per page
     * @param {boolean} [pagination] Enable or disable pagination
     * @param {string} [user] 
     * @param {Array<string>} [user] 
     * @param {string} [termsOfUse] 
     * @param {Array<string>} [termsOfUse] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserTermsOfUseApi
     */
    public async getUserTermsOfUseCollection(page?: number, itemsPerPage?: number, pagination?: boolean, user?: string, user?: Array<string>, termsOfUse?: string, termsOfUse?: Array<string>, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse20082>> {
        return UserTermsOfUseApiFp(this.configuration).getUserTermsOfUseCollection(page, itemsPerPage, pagination, user, user, termsOfUse, termsOfUse, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Retrieves a UserTermsOfUse resource.
     * @summary Retrieves a UserTermsOfUse resource.
     * @param {string} id Resource identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserTermsOfUseApi
     */
    public async getUserTermsOfUseItem(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<UserTermsOfUseJsonldUserTermsOfUseItemRead>> {
        return UserTermsOfUseApiFp(this.configuration).getUserTermsOfUseItem(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Creates a UserTermsOfUse resource.
     * @summary Creates a UserTermsOfUse resource.
     * @param {UserTermsOfUseJsonldUserTermsOfUseWrite} body The new UserTermsOfUse resource
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserTermsOfUseApi
     */
    public async postUserTermsOfUseCollection(body: UserTermsOfUseJsonldUserTermsOfUseWrite, options?: AxiosRequestConfig) : Promise<AxiosResponse<UserTermsOfUseJsonld>> {
        return UserTermsOfUseApiFp(this.configuration).postUserTermsOfUseCollection(body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Creates a UserTermsOfUse resource.
     * @summary Creates a UserTermsOfUse resource.
     * @param {UserTermsOfUseJsonldUserTermsOfUseWrite} body The new UserTermsOfUse resource
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserTermsOfUseApi
     */
    public async postUserTermsOfUseCollection(body: UserTermsOfUseJsonldUserTermsOfUseWrite, options?: AxiosRequestConfig) : Promise<AxiosResponse<UserTermsOfUseJsonld>> {
        return UserTermsOfUseApiFp(this.configuration).postUserTermsOfUseCollection(body, options).then((request) => request(this.axios, this.basePath));
    }
}
