/* tslint:disable */
/* eslint-disable */
/**
 * MLS2 API
 * Central API
 *
 * OpenAPI spec version: 0.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { InlineResponse20079 } from '../models';
import { UserInvitationJsonld } from '../models';
import { UserInvitationJsonldUserInvitationItemRead } from '../models';
import { UserInvitationJsonldUserInvitationItemWrite } from '../models';
import { UserInvitationJsonldUserInvitationWrite } from '../models';
import { UserInvitationUserInvitationItemWrite } from '../models';
import { UserInvitationUserInvitationWrite } from '../models';
/**
 * UserInvitationApi - axios parameter creator
 * @export
 */
export const UserInvitationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Removes the UserInvitation resource.
         * @summary Removes the UserInvitation resource.
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteUserInvitationItem: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling deleteUserInvitationItem.');
            }
            const localVarPath = `/mls-api/user-invitations/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("oauth", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves the collection of UserInvitation resources.
         * @summary Retrieves the collection of UserInvitation resources.
         * @param {number} [page] The collection page number
         * @param {number} [itemsPerPage] The number of items per page
         * @param {boolean} [pagination] Enable or disable pagination
         * @param {string} [organization] 
         * @param {Array<string>} [organization] 
         * @param {string} [groups] 
         * @param {Array<string>} [groups] 
         * @param {string} [invitor] 
         * @param {Array<string>} [invitor] 
         * @param {string} [code] 
         * @param {Array<string>} [code] 
         * @param {boolean} [approved] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserInvitationCollection: async (page?: number, itemsPerPage?: number, pagination?: boolean, organization?: string, organization?: Array<string>, groups?: string, groups?: Array<string>, invitor?: string, invitor?: Array<string>, code?: string, code?: Array<string>, approved?: boolean, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/mls-api/user-invitations`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("oauth", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (itemsPerPage !== undefined) {
                localVarQueryParameter['itemsPerPage'] = itemsPerPage;
            }

            if (pagination !== undefined) {
                localVarQueryParameter['pagination'] = pagination;
            }

            if (organization !== undefined) {
                localVarQueryParameter['organization'] = organization;
            }

            if (organization) {
                localVarQueryParameter['organization[]'] = organization;
            }

            if (groups !== undefined) {
                localVarQueryParameter['groups'] = groups;
            }

            if (groups) {
                localVarQueryParameter['groups[]'] = groups;
            }

            if (invitor !== undefined) {
                localVarQueryParameter['invitor'] = invitor;
            }

            if (invitor) {
                localVarQueryParameter['invitor[]'] = invitor;
            }

            if (code !== undefined) {
                localVarQueryParameter['code'] = code;
            }

            if (code) {
                localVarQueryParameter['code[]'] = code;
            }

            if (approved !== undefined) {
                localVarQueryParameter['approved'] = approved;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves a UserInvitation resource.
         * @summary Retrieves a UserInvitation resource.
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserInvitationItem: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling getUserInvitationItem.');
            }
            const localVarPath = `/mls-api/user-invitations/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("oauth", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Creates a UserInvitation resource.
         * @summary Creates a UserInvitation resource.
         * @param {UserInvitationJsonldUserInvitationWrite} body The new UserInvitation resource
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postUserInvitationCollection: async (body: UserInvitationJsonldUserInvitationWrite, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling postUserInvitationCollection.');
            }
            const localVarPath = `/mls-api/user-invitations`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("oauth", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/ld+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Creates a UserInvitation resource.
         * @summary Creates a UserInvitation resource.
         * @param {UserInvitationJsonldUserInvitationWrite} body The new UserInvitation resource
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postUserInvitationCollection: async (body: UserInvitationJsonldUserInvitationWrite, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling postUserInvitationCollection.');
            }
            const localVarPath = `/mls-api/user-invitations`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("oauth", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/ld+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Replaces the UserInvitation resource.
         * @summary Replaces the UserInvitation resource.
         * @param {UserInvitationJsonldUserInvitationItemWrite} body The updated UserInvitation resource
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putUserInvitationItem: async (body: UserInvitationJsonldUserInvitationItemWrite, id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling putUserInvitationItem.');
            }
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling putUserInvitationItem.');
            }
            const localVarPath = `/mls-api/user-invitations/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("oauth", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/ld+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Replaces the UserInvitation resource.
         * @summary Replaces the UserInvitation resource.
         * @param {UserInvitationJsonldUserInvitationItemWrite} body The updated UserInvitation resource
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putUserInvitationItem: async (body: UserInvitationJsonldUserInvitationItemWrite, id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling putUserInvitationItem.');
            }
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling putUserInvitationItem.');
            }
            const localVarPath = `/mls-api/user-invitations/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("oauth", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/ld+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserInvitationApi - functional programming interface
 * @export
 */
export const UserInvitationApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Removes the UserInvitation resource.
         * @summary Removes the UserInvitation resource.
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteUserInvitationItem(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await UserInvitationApiAxiosParamCreator(configuration).deleteUserInvitationItem(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Retrieves the collection of UserInvitation resources.
         * @summary Retrieves the collection of UserInvitation resources.
         * @param {number} [page] The collection page number
         * @param {number} [itemsPerPage] The number of items per page
         * @param {boolean} [pagination] Enable or disable pagination
         * @param {string} [organization] 
         * @param {Array<string>} [organization] 
         * @param {string} [groups] 
         * @param {Array<string>} [groups] 
         * @param {string} [invitor] 
         * @param {Array<string>} [invitor] 
         * @param {string} [code] 
         * @param {Array<string>} [code] 
         * @param {boolean} [approved] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserInvitationCollection(page?: number, itemsPerPage?: number, pagination?: boolean, organization?: string, organization?: Array<string>, groups?: string, groups?: Array<string>, invitor?: string, invitor?: Array<string>, code?: string, code?: Array<string>, approved?: boolean, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse20079>>> {
            const localVarAxiosArgs = await UserInvitationApiAxiosParamCreator(configuration).getUserInvitationCollection(page, itemsPerPage, pagination, organization, organization, groups, groups, invitor, invitor, code, code, approved, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Retrieves a UserInvitation resource.
         * @summary Retrieves a UserInvitation resource.
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserInvitationItem(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<UserInvitationJsonldUserInvitationItemRead>>> {
            const localVarAxiosArgs = await UserInvitationApiAxiosParamCreator(configuration).getUserInvitationItem(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Creates a UserInvitation resource.
         * @summary Creates a UserInvitation resource.
         * @param {UserInvitationJsonldUserInvitationWrite} body The new UserInvitation resource
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postUserInvitationCollection(body: UserInvitationJsonldUserInvitationWrite, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<UserInvitationJsonld>>> {
            const localVarAxiosArgs = await UserInvitationApiAxiosParamCreator(configuration).postUserInvitationCollection(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Creates a UserInvitation resource.
         * @summary Creates a UserInvitation resource.
         * @param {UserInvitationJsonldUserInvitationWrite} body The new UserInvitation resource
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postUserInvitationCollection(body: UserInvitationJsonldUserInvitationWrite, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<UserInvitationJsonld>>> {
            const localVarAxiosArgs = await UserInvitationApiAxiosParamCreator(configuration).postUserInvitationCollection(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Replaces the UserInvitation resource.
         * @summary Replaces the UserInvitation resource.
         * @param {UserInvitationJsonldUserInvitationItemWrite} body The updated UserInvitation resource
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putUserInvitationItem(body: UserInvitationJsonldUserInvitationItemWrite, id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<UserInvitationJsonld>>> {
            const localVarAxiosArgs = await UserInvitationApiAxiosParamCreator(configuration).putUserInvitationItem(body, id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Replaces the UserInvitation resource.
         * @summary Replaces the UserInvitation resource.
         * @param {UserInvitationJsonldUserInvitationItemWrite} body The updated UserInvitation resource
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putUserInvitationItem(body: UserInvitationJsonldUserInvitationItemWrite, id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<UserInvitationJsonld>>> {
            const localVarAxiosArgs = await UserInvitationApiAxiosParamCreator(configuration).putUserInvitationItem(body, id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * UserInvitationApi - factory interface
 * @export
 */
export const UserInvitationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Removes the UserInvitation resource.
         * @summary Removes the UserInvitation resource.
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteUserInvitationItem(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return UserInvitationApiFp(configuration).deleteUserInvitationItem(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves the collection of UserInvitation resources.
         * @summary Retrieves the collection of UserInvitation resources.
         * @param {number} [page] The collection page number
         * @param {number} [itemsPerPage] The number of items per page
         * @param {boolean} [pagination] Enable or disable pagination
         * @param {string} [organization] 
         * @param {Array<string>} [organization] 
         * @param {string} [groups] 
         * @param {Array<string>} [groups] 
         * @param {string} [invitor] 
         * @param {Array<string>} [invitor] 
         * @param {string} [code] 
         * @param {Array<string>} [code] 
         * @param {boolean} [approved] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserInvitationCollection(page?: number, itemsPerPage?: number, pagination?: boolean, organization?: string, organization?: Array<string>, groups?: string, groups?: Array<string>, invitor?: string, invitor?: Array<string>, code?: string, code?: Array<string>, approved?: boolean, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse20079>> {
            return UserInvitationApiFp(configuration).getUserInvitationCollection(page, itemsPerPage, pagination, organization, organization, groups, groups, invitor, invitor, code, code, approved, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves a UserInvitation resource.
         * @summary Retrieves a UserInvitation resource.
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserInvitationItem(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<UserInvitationJsonldUserInvitationItemRead>> {
            return UserInvitationApiFp(configuration).getUserInvitationItem(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Creates a UserInvitation resource.
         * @summary Creates a UserInvitation resource.
         * @param {UserInvitationJsonldUserInvitationWrite} body The new UserInvitation resource
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postUserInvitationCollection(body: UserInvitationJsonldUserInvitationWrite, options?: AxiosRequestConfig): Promise<AxiosResponse<UserInvitationJsonld>> {
            return UserInvitationApiFp(configuration).postUserInvitationCollection(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Creates a UserInvitation resource.
         * @summary Creates a UserInvitation resource.
         * @param {UserInvitationJsonldUserInvitationWrite} body The new UserInvitation resource
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postUserInvitationCollection(body: UserInvitationJsonldUserInvitationWrite, options?: AxiosRequestConfig): Promise<AxiosResponse<UserInvitationJsonld>> {
            return UserInvitationApiFp(configuration).postUserInvitationCollection(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Replaces the UserInvitation resource.
         * @summary Replaces the UserInvitation resource.
         * @param {UserInvitationJsonldUserInvitationItemWrite} body The updated UserInvitation resource
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putUserInvitationItem(body: UserInvitationJsonldUserInvitationItemWrite, id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<UserInvitationJsonld>> {
            return UserInvitationApiFp(configuration).putUserInvitationItem(body, id, options).then((request) => request(axios, basePath));
        },
        /**
         * Replaces the UserInvitation resource.
         * @summary Replaces the UserInvitation resource.
         * @param {UserInvitationJsonldUserInvitationItemWrite} body The updated UserInvitation resource
         * @param {string} id Resource identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putUserInvitationItem(body: UserInvitationJsonldUserInvitationItemWrite, id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<UserInvitationJsonld>> {
            return UserInvitationApiFp(configuration).putUserInvitationItem(body, id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserInvitationApi - object-oriented interface
 * @export
 * @class UserInvitationApi
 * @extends {BaseAPI}
 */
export class UserInvitationApi extends BaseAPI {
    /**
     * Removes the UserInvitation resource.
     * @summary Removes the UserInvitation resource.
     * @param {string} id Resource identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserInvitationApi
     */
    public async deleteUserInvitationItem(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return UserInvitationApiFp(this.configuration).deleteUserInvitationItem(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Retrieves the collection of UserInvitation resources.
     * @summary Retrieves the collection of UserInvitation resources.
     * @param {number} [page] The collection page number
     * @param {number} [itemsPerPage] The number of items per page
     * @param {boolean} [pagination] Enable or disable pagination
     * @param {string} [organization] 
     * @param {Array<string>} [organization] 
     * @param {string} [groups] 
     * @param {Array<string>} [groups] 
     * @param {string} [invitor] 
     * @param {Array<string>} [invitor] 
     * @param {string} [code] 
     * @param {Array<string>} [code] 
     * @param {boolean} [approved] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserInvitationApi
     */
    public async getUserInvitationCollection(page?: number, itemsPerPage?: number, pagination?: boolean, organization?: string, organization?: Array<string>, groups?: string, groups?: Array<string>, invitor?: string, invitor?: Array<string>, code?: string, code?: Array<string>, approved?: boolean, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse20079>> {
        return UserInvitationApiFp(this.configuration).getUserInvitationCollection(page, itemsPerPage, pagination, organization, organization, groups, groups, invitor, invitor, code, code, approved, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Retrieves a UserInvitation resource.
     * @summary Retrieves a UserInvitation resource.
     * @param {string} id Resource identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserInvitationApi
     */
    public async getUserInvitationItem(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<UserInvitationJsonldUserInvitationItemRead>> {
        return UserInvitationApiFp(this.configuration).getUserInvitationItem(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Creates a UserInvitation resource.
     * @summary Creates a UserInvitation resource.
     * @param {UserInvitationJsonldUserInvitationWrite} body The new UserInvitation resource
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserInvitationApi
     */
    public async postUserInvitationCollection(body: UserInvitationJsonldUserInvitationWrite, options?: AxiosRequestConfig) : Promise<AxiosResponse<UserInvitationJsonld>> {
        return UserInvitationApiFp(this.configuration).postUserInvitationCollection(body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Creates a UserInvitation resource.
     * @summary Creates a UserInvitation resource.
     * @param {UserInvitationJsonldUserInvitationWrite} body The new UserInvitation resource
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserInvitationApi
     */
    public async postUserInvitationCollection(body: UserInvitationJsonldUserInvitationWrite, options?: AxiosRequestConfig) : Promise<AxiosResponse<UserInvitationJsonld>> {
        return UserInvitationApiFp(this.configuration).postUserInvitationCollection(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Replaces the UserInvitation resource.
     * @summary Replaces the UserInvitation resource.
     * @param {UserInvitationJsonldUserInvitationItemWrite} body The updated UserInvitation resource
     * @param {string} id Resource identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserInvitationApi
     */
    public async putUserInvitationItem(body: UserInvitationJsonldUserInvitationItemWrite, id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<UserInvitationJsonld>> {
        return UserInvitationApiFp(this.configuration).putUserInvitationItem(body, id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Replaces the UserInvitation resource.
     * @summary Replaces the UserInvitation resource.
     * @param {UserInvitationJsonldUserInvitationItemWrite} body The updated UserInvitation resource
     * @param {string} id Resource identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserInvitationApi
     */
    public async putUserInvitationItem(body: UserInvitationJsonldUserInvitationItemWrite, id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<UserInvitationJsonld>> {
        return UserInvitationApiFp(this.configuration).putUserInvitationItem(body, id, options).then((request) => request(this.axios, this.basePath));
    }
}
